"""Semantic contract for the `autopilot` catalog skill."""

from __future__ import annotations

from catalog_core import SKILLS_DIR, errors

SKILL = "autopilot"
REQUIRED_PATHS = ["SKILL.md", "references/resume-and-recovery.md", "scripts/autopilot_state.py"]
REQUIRED_TEXT = [
    "clarify → plan → implement → verify → deliver → done",
    "Generated by scripts/generate_workflow_runtimes.py",
    "agent-workflow-response/2",
    "--expected-revision",
    "plan --path <existing-file>",
    "list --all-sessions",
    "doctor",
    "recover",
    "unlock",
    ".agent-workflows/autopilot/<session>/<id>.json",
    "PairRoom",
    "second enters terminal **blocked**",
]
FORBIDDEN_TEXT = (
    "oma ",
    ".oma/",
    "oh-my-agents",
    'AUTOPILOT="python',
    "missing-plan.md\" will be accepted",
)


def validate(*, readme_text: str | None = None) -> None:
    skill_dir = SKILLS_DIR / SKILL
    missing = [relative for relative in REQUIRED_PATHS if not (skill_dir / relative).is_file()]
    if missing:
        errors.append(f"{SKILL}: missing required migration payload: {missing}")
        return
    text = "\n".join((skill_dir / relative).read_text(encoding="utf-8") for relative in REQUIRED_PATHS)
    absent = [fixture for fixture in REQUIRED_TEXT if fixture not in text]
    if absent:
        errors.append(f"{SKILL}: semantic migration fixtures missing: {absent}")
    lowered = text.lower()
    found = [fixture for fixture in FORBIDDEN_TEXT if fixture.lower() in lowered]
    if found:
        errors.append(f"{SKILL}: migrated payload retains unsafe or retired behavior: {found}")
