"""Targeted executable/safety contract for the `autopilot` skill."""

from __future__ import annotations

from catalog_core import SKILLS_DIR, errors

SKILL = "autopilot"
REQUIRED_PATHS = (
    "SKILL.md",
    "references/persistent-runtime.md",
    "references/resume-and-recovery.md",
    "scripts/autopilot_state.py",
)
REQUIRED_POLICY_TEXT = (
    "Default to the native Agent loop",
    "Use the persistent runtime only when",
    "read its control-plane reference",
    "Delivery does not imply merge, push, deployment, publication",
    "work-protocol",
)
REQUIRED_RUNTIME_TEXT = (
    "Generated by scripts/generate_workflow_runtimes.py",
    "agent-workflow-response/2",
    "--expected-revision",
    "plan --path <existing-file>",
    "actually observed result",
    "list --all-sessions",
    "doctor",
    "recover",
    "unlock",
    ".agent-workflows/autopilot/<session>/<id>.json",
)
FORBIDDEN_TEXT = (
    "oma ",
    ".oma/",
    "oh-my-agents",
    'AUTOPILOT="python',
    "missing-plan.md\" will be accepted",
)

def validate(*, readme_text: str | None = None) -> None:
    skill_dir = SKILLS_DIR / SKILL
    missing = [relative for relative in REQUIRED_PATHS if not (skill_dir / relative).is_file()]
    if missing:
        errors.append(f"{SKILL}: missing required runtime payload: {missing}")
        return

    skill_text = (skill_dir / "SKILL.md").read_text(encoding="utf-8")
    runtime_text = "\n".join(
        (skill_dir / relative).read_text(encoding="utf-8")
        for relative in REQUIRED_PATHS[1:]
    )
    absent_policy = [fixture for fixture in REQUIRED_POLICY_TEXT if fixture not in skill_text]
    absent_runtime = [fixture for fixture in REQUIRED_RUNTIME_TEXT if fixture not in runtime_text]
    if absent_policy or absent_runtime:
        errors.append(
            f"{SKILL}: optional-runtime or safety fixtures missing: "
            f"policy={absent_policy}, runtime={absent_runtime}"
        )

    lowered = f"{skill_text}\n{runtime_text}".lower()
    found = [fixture for fixture in FORBIDDEN_TEXT if fixture.lower() in lowered]
    if found:
        errors.append(f"{SKILL}: payload retains unsafe or retired behavior: {found}")
