"""Semantic contract for the `deep-interview` catalog skill."""

from __future__ import annotations

from catalog_core import SKILLS_DIR, errors

SKILL = "deep-interview"
REQUIRED_PATHS = [
    "SKILL.md",
    "references/scoring-and-payloads.md",
    "references/resume-and-recovery.md",
    "scripts/interview_state.py",
]
REQUIRED_TEXT = [
    "Generated by scripts/generate_workflow_runtimes.py",
    "agent-workflow-response/2",
    "agent-interview-topology/2",
    "agent-interview-round/2",
    "greenfield ambiguity = 1 - (goal×0.40 + constraints×0.30 + criteria×0.30)",
    "brownfield ambiguity = 1 - (goal×0.35 + constraints×0.25 + criteria×0.25 + context×0.15)",
    "component × dimension",
    "challenge_mode_used",
    "metrics.cadence_user_required",
    "scope boundary, acceptance criterion, rollback contract, lane assignment, or handoff target",
    "Round 20 is a hard scoring cap",
    "crystallize",
    "approve",
    "complete",
    "pending approval",
    ".agent-workflows/deep-interview/<session>/<id>.json",
    "Never hand-calculate ambiguity",
]
FORBIDDEN_TEXT = (
    "oma ",
    ".oma/",
    "oh-my-agents",
    'INTERVIEW="python',
    "0.6 × (1 - mean(scores))",
    "complete --spec-path",
)


def validate(*, readme_text: str | None = None) -> None:
    skill_dir = SKILLS_DIR / SKILL
    missing = [relative for relative in REQUIRED_PATHS if not (skill_dir / relative).is_file()]
    if missing:
        errors.append(f"{SKILL}: missing required migration payload: {missing}")
        return
    text = "\n".join((skill_dir / relative).read_text(encoding="utf-8") for relative in REQUIRED_PATHS)
    absent = [fixture for fixture in REQUIRED_TEXT if fixture not in text]
    if absent:
        errors.append(f"{SKILL}: semantic migration fixtures missing: {absent}")
    lowered = text.lower()
    found = [fixture for fixture in FORBIDDEN_TEXT if fixture.lower() in lowered]
    if found:
        errors.append(f"{SKILL}: migrated payload retains unsafe or incompatible behavior: {found}")
