"""Targeted executable/approval contract for the `deep-interview` skill."""

from __future__ import annotations

from catalog_core import SKILLS_DIR, errors

SKILL = "deep-interview"
REQUIRED_PATHS = (
    "SKILL.md",
    "references/persistent-runtime.md",
    "references/scoring-and-payloads.md",
    "references/resume-and-recovery.md",
    "scripts/interview_state.py",
)
REQUIRED_RUNTIME_TEXT = (
    "Generated by scripts/generate_workflow_runtimes.py",
    "agent-workflow-response/2",
    "agent-interview-topology/2",
    "agent-interview-round/2",
    "component × dimension",
    "crystallize --spec-path <existing-file>",
    "challenge_mode_used",
    "metrics.cadence_user_required",
    ".agent-workflows/deep-interview/<session>/<id>.json",
)
FORBIDDEN_TEXT = (
    "oma ",
    ".oma/",
    "oh-my-agents",
    'INTERVIEW="python',
    "0.6 × (1 - mean(scores))",
    "complete --spec-path",
)


def validate(*, readme_text: str | None = None) -> None:
    skill_dir = SKILLS_DIR / SKILL
    missing = [relative for relative in REQUIRED_PATHS if not (skill_dir / relative).is_file()]
    if missing:
        errors.append(f"{SKILL}: missing required runtime payload: {missing}")
        return

    runtime_text = "\n".join(
        (skill_dir / relative).read_text(encoding="utf-8")
        for relative in REQUIRED_PATHS[1:]
    )
    absent_runtime = [fixture for fixture in REQUIRED_RUNTIME_TEXT if fixture not in runtime_text]
    if absent_runtime:
        errors.append(
            f"{SKILL}: persistent-runtime executable fixtures missing: {absent_runtime}"
        )

    payload_text = "\n".join(
        (skill_dir / relative).read_text(encoding="utf-8") for relative in REQUIRED_PATHS
    )
    lowered = payload_text.lower()
    found = [fixture for fixture in FORBIDDEN_TEXT if fixture.lower() in lowered]
    if found:
        errors.append(f"{SKILL}: payload retains unsafe or incompatible behavior: {found}")
