"""Semantic contract for the `work-protocol` catalog skill."""

from __future__ import annotations

from catalog_core import SKILLS_DIR, errors

SKILL = "work-protocol"
REQUIRED_PATHS = [
    "SKILL.md",
    "references/task-state-and-evidence.md",
    "references/workspace-isolation.md",
    "scripts/workctl.py",
    "scripts/work_protocol_runtime/common.py",
    "scripts/work_protocol_runtime/workctl.py",
]
REQUIRED_TEXT = [
    "Generated by scripts/generate_p0_runtimes.py",
    "agent-work/v1",
    ".agents/work/<task-id>/brief.md",
    "--expect-version",
    "WORKSPACE_ROLES",
    "verify_retry_count",
    "workspace_changed_paths",
    "base_commit",
    "--diff-filter=U",
]


def validate(*, readme_text: str | None = None) -> None:
    skill_dir = SKILLS_DIR / SKILL
    missing = [relative for relative in REQUIRED_PATHS if not (skill_dir / relative).is_file()]
    if missing:
        errors.append(f"{SKILL}: missing required work-protocol payload: {missing}")
        return
    text = "\n".join((skill_dir / relative).read_text(encoding="utf-8") for relative in REQUIRED_PATHS)
    lowered = text.lower()
    absent = [fixture for fixture in REQUIRED_TEXT if fixture.lower() not in lowered]
    if absent:
        errors.append(f"{SKILL}: work-protocol contract fixtures missing: {absent}")
