"""Semantic contract for the `work-protocol` catalog skill."""

from __future__ import annotations

from catalog_core import SKILLS_DIR, errors

SKILL = "work-protocol"
REQUIRED_PATHS = [
    "SKILL.md",
    "references/task-state-and-evidence.md",
    "references/workspace-isolation.md",
    "scripts/workctl.py",
    "scripts/work_protocol_runtime/common.py",
    "scripts/work_protocol_runtime/workctl.py",
]
REQUIRED_TEXT = [
    "Generated by scripts/generate_p0_runtimes.py",
    "agent-work/v1",
    ".agents/work/<task-id>/brief.md",
    "single loop owner",
    "--expect-version",
    "owner recover",
    "owner check",
    "owner heartbeat",
    "owner-heartbeat",
    "hash-chained evidence",
    "git common directory",
    "exact full commit sha",
    "at most one integrator",
    "WORKSPACE_ROLES",
    "verify_retry_count",
    "latest deterministic verification",
    "workspace_changed_paths",
    "base_commit",
    "--diff-filter=U",
]


def validate(*, readme_text: str | None = None) -> None:
    skill_dir = SKILLS_DIR / SKILL
    missing = [relative for relative in REQUIRED_PATHS if not (skill_dir / relative).is_file()]
    if missing:
        errors.append(f"{SKILL}: missing required work-protocol payload: {missing}")
        return
    text = "\n".join((skill_dir / relative).read_text(encoding="utf-8") for relative in REQUIRED_PATHS)
    lowered = text.lower()
    absent = [fixture for fixture in REQUIRED_TEXT if fixture.lower() not in lowered]
    if absent:
        errors.append(f"{SKILL}: work-protocol contract fixtures missing: {absent}")
    required_negations = (
        "do not let two writers share one writable worktree",
        "expired lease is not silently stolen",
        "do not edit `state.json`",
    )
    missing_negations = [fixture for fixture in required_negations if fixture not in lowered]
    if missing_negations:
        errors.append(f"{SKILL}: work-protocol safety negations missing: {missing_negations}")
    loop_boundaries = {
        "autopilot": "explicit `autopilot` owner lease",
        "ralph": "explicit `ralph` owner lease",
    }
    for loop_skill, marker in loop_boundaries.items():
        path = SKILLS_DIR / loop_skill / "SKILL.md"
        if not path.is_file() or marker not in path.read_text(encoding="utf-8"):
            errors.append(f"{SKILL}: {loop_skill} is missing its thin loop-owner boundary")
