#!/usr/bin/env python3
# Generated by scripts/generate_workflow_runtimes.py. Do not edit this file directly.
# Source: scripts/workflow_runtime/common.py + scripts/workflow_runtime/ralph.py

from __future__ import annotations

import argparse
import contextlib
import datetime as dt
import hashlib
import json
import math
import os
import re
import secrets
import shutil
import subprocess
import sys
import tempfile
import traceback
from pathlib import Path
from typing import Any, Dict, Iterator, List, Optional, Sequence, Tuple

RESPONSE_SCHEMA = "agent-workflow-response/2"
STATE_ROOT_NAME = ".agent-workflows"
ID_RE = re.compile(r"[a-z0-9][a-z0-9._-]{0,63}")
SESSION_RE = re.compile(r"[a-z0-9][a-z0-9._-]{0,63}")
MAX_STATE_BYTES = 2 * 1024 * 1024
MAX_INPUT_JSON_BYTES = 128 * 1024
DEFAULT_HISTORY_TAIL = 5
MAX_HISTORY_TAIL = 20
DEFAULT_LIST_LIMIT = 20
MAX_LIST_LIMIT = 100
WINDOWS_RESERVED_SEGMENTS = {
    "CON",
    "PRN",
    "AUX",
    "NUL",
    *("COM%d" % value for value in range(1, 10)),
    *("LPT%d" % value for value in range(1, 10)),
}


class WorkflowError(Exception):
    def __init__(self, code: int, kind: str, message: str, **details: Any) -> None:
        super().__init__(message)
        self.code = code
        self.kind = kind
        self.message = message
        self.details = details


class JsonArgumentParser(argparse.ArgumentParser):
    def error(self, message: str) -> None:
        raise WorkflowError(2, "usage", message)


def now() -> str:
    return dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()


def parse_time(value: Any) -> Optional[dt.datetime]:
    if not isinstance(value, str):
        return None
    try:
        parsed = dt.datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None
    if parsed.tzinfo is None or parsed.utcoffset() is None:
        return None
    return parsed.astimezone(dt.timezone.utc)


def configure_streams() -> None:
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure is not None:
            try:
                reconfigure(encoding="utf-8", errors="replace")
            except (AttributeError, OSError, ValueError):
                pass


def reject_json_constant(value: str) -> Any:
    raise ValueError("non-standard JSON constant: %s" % value)


def emit(payload: Dict[str, Any], *, stream: Any = sys.stdout) -> None:
    print(
        json.dumps(
            payload,
            ensure_ascii=False,
            sort_keys=True,
            allow_nan=False,
            separators=(",", ":"),
        ),
        file=stream,
    )


def bounded_text(
    value: Any,
    field: str,
    limit: int,
    *,
    allow_empty: bool = False,
) -> str:
    if not isinstance(value, str):
        raise WorkflowError(2, "invalid_input", "%s must be text" % field, field=field)
    text = value.strip()
    if not allow_empty and not text:
        raise WorkflowError(2, "invalid_input", "%s must not be empty" % field, field=field)
    if len(text) > limit:
        raise WorkflowError(
            2,
            "input_too_long",
            "%s exceeds its character limit" % field,
            field=field,
            limit=limit,
            actual=len(text),
        )
    return text


def validate_string_list(
    value: Any,
    field: str,
    *,
    max_items: int,
    item_limit: int,
) -> List[str]:
    if not isinstance(value, list) or len(value) > max_items:
        raise WorkflowError(
            2,
            "invalid_input",
            "%s must be a list with at most %d items" % (field, max_items),
            field=field,
        )
    return [bounded_text(item, "%s[%d]" % (field, index), item_limit) for index, item in enumerate(value)]


def require_dict(value: Any, field: str) -> Dict[str, Any]:
    if not isinstance(value, dict):
        raise WorkflowError(6, "corrupt_state", "%s must be an object" % field, field=field)
    return value


def require_list(value: Any, field: str) -> List[Any]:
    if not isinstance(value, list):
        raise WorkflowError(6, "corrupt_state", "%s must be a list" % field, field=field)
    return value


def require_str(value: Any, field: str, *, allow_empty: bool = False) -> str:
    if not isinstance(value, str) or (not allow_empty and not value):
        raise WorkflowError(6, "corrupt_state", "%s must be text" % field, field=field)
    return value


def require_int(value: Any, field: str, *, minimum: Optional[int] = None) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise WorkflowError(6, "corrupt_state", "%s must be an integer" % field, field=field)
    if minimum is not None and value < minimum:
        raise WorkflowError(6, "corrupt_state", "%s is below its minimum" % field, field=field)
    return value


def require_timestamp(value: Any, field: str) -> str:
    text = require_str(value, field)
    if parse_time(text) is None:
        raise WorkflowError(6, "corrupt_state", "%s must be an offset-aware timestamp" % field, field=field)
    return text


def require_number(value: Any, field: str, *, nullable: bool = False) -> Optional[float]:
    if value is None and nullable:
        return None
    if isinstance(value, bool) or not isinstance(value, (int, float)) or not math.isfinite(float(value)):
        raise WorkflowError(6, "corrupt_state", "%s must be a finite number" % field, field=field)
    return float(value)


def safe_path_segment(value: str) -> bool:
    if value.endswith("."):
        return False
    stem = value.split(".", 1)[0].upper()
    return stem not in WINDOWS_RESERVED_SEGMENTS


def validate_id(value: str) -> str:
    if not ID_RE.fullmatch(value) or "--s-" in value or not safe_path_segment(value):
        raise WorkflowError(
            2,
            "invalid_id",
            "id must be a portable 1-64 character lowercase path segment using letters, digits, dot, underscore, or hyphen",
            value=value,
        )
    return value


def normalize_session(value: Optional[str]) -> str:
    raw = value
    if raw is None:
        for name in ("AGENT_WORKFLOW_SESSION", "CLAUDE_CODE_SESSION_ID", "CODEX_THREAD_ID"):
            candidate = os.environ.get(name, "").strip()
            if candidate:
                raw = candidate
                break
    raw = (raw or "current").strip()
    if SESSION_RE.fullmatch(raw) and "--s-" not in raw and safe_path_segment(raw):
        return raw
    digest = hashlib.sha256(raw.encode("utf-8")).hexdigest()[:16]
    return "session-%s" % digest


def run_git(cwd: Path, args: Sequence[str]) -> Optional[str]:
    try:
        cp = subprocess.run(
            ["git", "-C", str(cwd), *args],
            text=True,
            encoding="utf-8",
            errors="replace",
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            timeout=10,
            env=dict(os.environ, GIT_OPTIONAL_LOCKS="0", GIT_TERMINAL_PROMPT="0"),
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return None
    if cp.returncode != 0:
        return None
    return cp.stdout.strip()


def workspace_context(root_override: Optional[str]) -> Dict[str, str]:
    if root_override:
        root = Path(root_override).expanduser().resolve()
        if not root.is_dir():
            raise WorkflowError(6, "invalid_root", "--root must name an existing directory", path=str(root))
    else:
        root = Path.cwd().resolve()

    probe = run_git(
        root,
        [
            "rev-parse",
            "--show-toplevel",
            "--path-format=absolute",
            "--git-common-dir",
            "HEAD",
            "--abbrev-ref",
            "HEAD",
        ],
    )
    lines = probe.splitlines() if probe is not None else []
    if len(lines) >= 4:
        top, common_raw, commit, branch = lines[0], lines[1], lines[2], lines[3]
    else:
        top = run_git(root, ["rev-parse", "--show-toplevel"])
        common_raw = ""
        commit = ""
        branch = ""
    if top is None:
        return {
            "vcs": "none",
            "worktree": str(root),
            "branch": "NO_GIT",
            "base_commit": "",
            "repository_root": str(root),
        }

    worktree = Path(top).resolve()
    if not common_raw:
        common_raw = run_git(worktree, ["rev-parse", "--path-format=absolute", "--git-common-dir"]) or ""
    if common_raw:
        common = Path(common_raw).resolve()
    else:
        fallback = run_git(worktree, ["rev-parse", "--git-common-dir"])
        if fallback is None:
            common = worktree / ".git"
        else:
            raw_path = Path(fallback)
            common = raw_path.resolve() if raw_path.is_absolute() else (worktree / raw_path).resolve()
    if not commit:
        commit = run_git(worktree, ["rev-parse", "HEAD"]) or ""
    if not branch:
        branch = run_git(worktree, ["symbolic-ref", "--quiet", "--short", "HEAD"]) or ""
    if branch == "HEAD" or not branch:
        branch = "DETACHED:%s" % (commit[:12] or "unknown")
    repository_root = common.parent.resolve() if common.name == ".git" else worktree
    return {
        "vcs": "git",
        "worktree": str(worktree),
        "branch": branch,
        "base_commit": commit,
        "repository_root": str(repository_root),
    }


def new_binding(context: Dict[str, str]) -> Dict[str, str]:
    return {
        "vcs": context["vcs"],
        "worktree": context["worktree"],
        "branch": context["branch"],
        "base_commit": context["base_commit"],
    }


def binding_report(state: Dict[str, Any], context: Dict[str, str], *, full: bool = False) -> Dict[str, Any]:
    recorded = require_dict(state.get("binding"), "binding")
    ok = (
        recorded.get("vcs") == context["vcs"]
        and recorded.get("worktree") == context["worktree"]
        and recorded.get("branch") == context["branch"]
    )
    payload: Dict[str, Any] = {"ok": ok}
    if full or not ok:
        payload["recorded"] = recorded
        payload["current"] = {
            "vcs": context["vcs"],
            "worktree": context["worktree"],
            "branch": context["branch"],
        }
    return payload


def ensure_safe_directory(path: Path, *, create: bool) -> bool:
    # `Path.exists()` is false for a dangling symlink; inspect the link first
    # so a failed mutation is reported as unsafe instead of an internal mkdir
    # error.
    if path.is_symlink():
        raise WorkflowError(6, "unsafe_state_root", "workflow state directory is unsafe", path=str(path))
    if path.exists():
        if not path.is_dir():
            raise WorkflowError(6, "unsafe_state_root", "workflow state directory is unsafe", path=str(path))
        return True
    if not create:
        return False
    parent = path.parent
    if parent != path:
        ensure_safe_directory(parent, create=True)
    path.mkdir(exist_ok=True)
    if path.is_symlink() or not path.is_dir():
        raise WorkflowError(6, "unsafe_state_root", "workflow state directory is unsafe", path=str(path))
    return True


def workflow_root(context: Dict[str, str], workflow: str, session: str, *, create: bool) -> Path:
    base = Path(context["repository_root"]) / STATE_ROOT_NAME
    if not ensure_safe_directory(base, create=create):
        return base / workflow / session
    root = base / workflow
    if not ensure_safe_directory(root, create=create):
        return root / session
    session_root = root / session
    ensure_safe_directory(session_root, create=create)
    return session_root


def state_paths(
    context: Dict[str, str],
    workflow: str,
    session: str,
    run_id: str,
    *,
    create: bool,
) -> Tuple[Path, Path, Path]:
    root = workflow_root(context, workflow, session, create=create)
    path = root / (run_id + ".json")
    for candidate, kind in (
        (path, "unsafe_state_file"),
        (path.with_suffix(".json.bak"), "unsafe_state_file"),
        (path.with_suffix(".json.lock"), "unsafe_lock_file"),
    ):
        if candidate.is_symlink():
            raise WorkflowError(6, kind, "workflow state path must not be a symlink", path=str(candidate))
    return path, path.with_suffix(".json.bak"), path.with_suffix(".json.lock")


def read_json(path: Path, *, kind: str, max_bytes: int) -> Dict[str, Any]:
    try:
        size = path.stat().st_size
        if size > max_bytes:
            raise WorkflowError(6, kind, "JSON file exceeds its size limit", path=str(path), limit=max_bytes)
        value = json.loads(path.read_text(encoding="utf-8"), parse_constant=reject_json_constant)
    except WorkflowError:
        raise
    except (OSError, UnicodeError, json.JSONDecodeError, ValueError) as exc:
        raise WorkflowError(6, kind, "JSON file is unreadable", path=str(path), error=type(exc).__name__) from exc
    if not isinstance(value, dict):
        raise WorkflowError(6, kind, "JSON root must be an object", path=str(path))
    return value


def lexical_relative_to_root(path: Path, root: Path) -> Tuple[Path, Path]:
    bound_root = root.resolve()
    expected = os.path.normcase(str(bound_root))
    matched_root: Optional[Path] = None
    for ancestor in path.parents:
        try:
            resolved_ancestor = ancestor.resolve(strict=True)
        except (OSError, RuntimeError):
            continue
        if os.path.normcase(str(resolved_ancestor)) == expected:
            # Keep the outermost match so a descendant symlink that points back
            # to the worktree root remains part of the path checked below.
            matched_root = ancestor
    if matched_root is None:
        raise ValueError("path is outside the bound root")
    return matched_root, path.relative_to(matched_root)


def load_json_input(value: str, *, root: Path) -> Dict[str, Any]:
    bound_root = root.resolve()
    candidate = Path(value).expanduser()
    if not candidate.is_absolute():
        candidate = bound_root / candidate
    lexical = Path(os.path.abspath(str(candidate)))
    try:
        lexical_root, relative = lexical_relative_to_root(lexical, bound_root)
    except ValueError as exc:
        raise WorkflowError(2, "invalid_input_file", "input file must stay inside the bound worktree", path=value) from exc
    cursor = lexical_root
    for part in relative.parts:
        cursor = cursor / part
        if cursor.is_symlink():
            raise WorkflowError(2, "invalid_input_file", "input path must not traverse a symlink", path=str(lexical))
    try:
        path = lexical.resolve(strict=True)
    except (OSError, RuntimeError) as exc:
        raise WorkflowError(2, "invalid_input_file", "input file does not exist", path=str(lexical)) from exc
    if not path.is_file():
        raise WorkflowError(2, "invalid_input_file", "input must be a regular file", path=str(path))
    try:
        path.relative_to(bound_root)
    except ValueError as exc:
        raise WorkflowError(2, "invalid_input_file", "input file must stay inside the bound worktree", path=value) from exc
    try:
        return read_json(path, kind="invalid_input_file", max_bytes=MAX_INPUT_JSON_BYTES)
    except WorkflowError as exc:
        if exc.kind == "invalid_input_file":
            exc.code = 2
        raise


def validate_common_state(
    state: Dict[str, Any],
    *,
    workflow: str,
    schema: str,
    run_id: str,
    session: str,
    path: Path,
) -> None:
    if state.get("schema") != schema:
        raise WorkflowError(6, "corrupt_state", "unknown workflow state schema", path=str(path), schema=state.get("schema"))
    if state.get("workflow") != workflow or state.get("id") != run_id or state.get("session") != session:
        raise WorkflowError(6, "corrupt_state", "workflow identity does not match its state path", path=str(path))
    require_int(state.get("revision"), "revision", minimum=1)
    require_str(state.get("status"), "status")
    created_at = require_timestamp(state.get("created_at"), "created_at")
    updated_at = require_timestamp(state.get("updated_at"), "updated_at")
    created = parse_time(created_at)
    updated = parse_time(updated_at)
    if created is None or updated is None or updated < created:
        raise WorkflowError(6, "corrupt_state", "workflow timestamps are invalid", path=str(path))
    binding = require_dict(state.get("binding"), "binding")
    for field in ("vcs", "worktree", "branch", "base_commit"):
        text = require_str(binding.get(field), "binding.%s" % field, allow_empty=(field == "base_commit"))
        if len(text) > (4096 if field == "worktree" else 1024):
            raise WorkflowError(6, "corrupt_state", "binding field exceeds its limit", field=field)
    if binding["vcs"] not in {"git", "none"}:
        raise WorkflowError(6, "corrupt_state", "binding.vcs is invalid")
    recoveries = require_list(state.get("recoveries"), "recoveries")
    if len(recoveries) > 20:
        raise WorkflowError(6, "corrupt_state", "recoveries exceeds its bounded history", path=str(path))
    for index, raw in enumerate(recoveries):
        recovery = require_dict(raw, "recoveries[%d]" % index)
        if recovery.get("source") != "backup" or not isinstance(recovery.get("forced"), bool):
            raise WorkflowError(6, "corrupt_state", "recovery entry is invalid", index=index)
        if "rebound" in recovery and not isinstance(recovery.get("rebound"), bool):
            raise WorkflowError(6, "corrupt_state", "recovery rebind flag is invalid", index=index)
        if parse_time(recovery.get("at")) is None:
            raise WorkflowError(6, "corrupt_state", "recovery timestamp is invalid", index=index)
    validate_workflow_state(state)


def load_state(
    path: Path,
    backup: Path,
    workflow: str,
    schema: str,
    run_id: str,
    session: str,
) -> Dict[str, Any]:
    if not path.exists():
        raise WorkflowError(3, "not_found", "workflow run does not exist", workflow=workflow, session=session, id=run_id)
    if not path.is_file() or path.is_symlink():
        raise WorkflowError(6, "unsafe_state_file", "workflow state must be a regular non-symlink file", path=str(path))
    try:
        state = read_json(path, kind="corrupt_state", max_bytes=MAX_STATE_BYTES)
        validate_common_state(
            state,
            workflow=workflow,
            schema=schema,
            run_id=run_id,
            session=session,
            path=path,
        )
        return state
    except WorkflowError as exc:
        if exc.kind == "corrupt_state":
            exc.details.setdefault("backup", str(backup))
        raise


def fsync_directory(path: Path) -> None:
    if os.name == "nt":
        return
    try:
        fd = os.open(str(path), os.O_RDONLY)
    except OSError:
        return
    try:
        os.fsync(fd)
    except OSError:
        pass
    finally:
        os.close(fd)


def atomic_write(path: Path, payload: bytes) -> None:
    ensure_safe_directory(path.parent, create=True)
    fd, temp_name = tempfile.mkstemp(prefix=path.name + ".", suffix=".tmp", dir=str(path.parent))
    temp_path = Path(temp_name)
    try:
        try:
            os.fchmod(fd, 0o600)
        except (AttributeError, OSError):
            pass
        with os.fdopen(fd, "wb") as fh:
            fh.write(payload)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(str(temp_path), str(path))
        try:
            os.chmod(path, 0o600)
        except OSError:
            pass
        fsync_directory(path.parent)
    finally:
        try:
            temp_path.unlink()
        except FileNotFoundError:
            pass


def save_state(path: Path, backup: Path, state: Dict[str, Any]) -> None:
    state["updated_at"] = now()
    validate_common_state(
        state,
        workflow=state["workflow"],
        schema=state["schema"],
        run_id=state["id"],
        session=state["session"],
        path=path,
    )
    if path.exists():
        if path.is_symlink() or not path.is_file():
            raise WorkflowError(6, "unsafe_state_file", "workflow state must be a regular file", path=str(path))
        atomic_write(backup, path.read_bytes())
    payload = (
        json.dumps(state, ensure_ascii=False, indent=2, sort_keys=True, allow_nan=False) + "\n"
    ).encode("utf-8")
    atomic_write(path, payload)


def pid_alive(pid: Any) -> bool:
    if isinstance(pid, bool) or not isinstance(pid, int) or pid <= 0:
        return False
    if pid == os.getpid():
        return True
    if os.name == "nt":
        # os.kill(pid, 0) is not a harmless existence probe on Windows: Python
        # maps non-console signals to TerminateProcess. Query a limited process
        # handle instead and treat access denied as evidence that the PID exists.
        import ctypes
        from ctypes import wintypes

        process_query_limited_information = 0x1000
        kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
        open_process = kernel32.OpenProcess
        open_process.argtypes = [wintypes.DWORD, wintypes.BOOL, wintypes.DWORD]
        open_process.restype = wintypes.HANDLE
        close_handle = kernel32.CloseHandle
        close_handle.argtypes = [wintypes.HANDLE]
        close_handle.restype = wintypes.BOOL
        ctypes.set_last_error(0)
        handle = open_process(process_query_limited_information, False, pid)
        if handle:
            close_handle(handle)
            return True
        return ctypes.get_last_error() == 5  # ERROR_ACCESS_DENIED
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    except OSError:
        return False
    return True


def lock_details(lock_path: Path) -> Dict[str, Any]:
    details: Dict[str, Any] = {"exists": lock_path.exists(), "path": str(lock_path)}
    if not lock_path.exists():
        return details
    if lock_path.is_symlink() or not lock_path.is_file():
        details.update({"safe": False, "owner": None, "alive": False, "age_seconds": None})
        return details
    try:
        owner = read_json(lock_path, kind="invalid_lock", max_bytes=16 * 1024)
    except WorkflowError:
        details.update({"safe": False, "owner": None, "alive": False, "age_seconds": None})
        return details
    created = parse_time(owner.get("created_at"))
    age = None
    if created is not None:
        age = max(0, int((dt.datetime.now(dt.timezone.utc) - created).total_seconds()))
    details.update({"safe": True, "owner": owner, "alive": pid_alive(owner.get("pid")), "age_seconds": age})
    return details


@contextlib.contextmanager
def command_lock(lock_path: Path) -> Iterator[None]:
    ensure_safe_directory(lock_path.parent, create=True)
    if lock_path.is_symlink():
        raise WorkflowError(6, "unsafe_lock_file", "workflow lock must not be a symlink", path=str(lock_path))
    owner = {
        "pid": os.getpid(),
        "token": secrets.token_hex(16),
        "created_at": now(),
        "cwd": str(Path.cwd().resolve()),
    }
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
    try:
        fd = os.open(str(lock_path), flags, 0o600)
    except FileExistsError as exc:
        raise WorkflowError(5, "locked", "another workflow mutation may be active", lock=lock_details(lock_path)) from exc
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as fh:
            json.dump(owner, fh, ensure_ascii=False, sort_keys=True, allow_nan=False)
            fh.write("\n")
            fh.flush()
            os.fsync(fh.fileno())
        yield
    finally:
        try:
            current = read_json(lock_path, kind="invalid_lock", max_bytes=16 * 1024)
            if current.get("token") == owner["token"]:
                lock_path.unlink()
        except (WorkflowError, FileNotFoundError):
            pass


def bump(state: Dict[str, Any]) -> None:
    state["revision"] += 1


def require_mutable(
    path: Path,
    backup: Path,
    run_id: str,
    session: str,
    expected_revision: int,
    context: Dict[str, str],
    *,
    allow_mismatch: bool = False,
) -> Dict[str, Any]:
    if expected_revision < 1:
        raise WorkflowError(2, "invalid_revision", "--expected-revision must be at least 1")
    state = load_state(path, backup, WORKFLOW, SCHEMA, run_id, session)
    if state["revision"] != expected_revision:
        raise WorkflowError(
            5,
            "revision_conflict",
            "state changed since it was read",
            expected=expected_revision,
            actual=state["revision"],
        )
    report = binding_report(state, context, full=True)
    if not allow_mismatch and not report["ok"]:
        raise WorkflowError(5, "binding_mismatch", "run is owned by another worktree or branch", binding=report)
    return state


def resolve_run_id(args: argparse.Namespace, context: Dict[str, str], session: str) -> str:
    explicit = getattr(args, "id", None)
    latest = bool(getattr(args, "latest", False))
    if explicit and latest:
        raise WorkflowError(2, "usage", "--id and --latest are mutually exclusive")
    if explicit:
        return validate_id(explicit)
    if latest:
        return latest_run_id(context, session)
    return "default"


def latest_run_id(context: Dict[str, str], session: str) -> str:
    root = workflow_root(context, WORKFLOW, session, create=False)
    if not root.is_dir():
        raise WorkflowError(3, "not_found", "no workflow runs exist", workflow=WORKFLOW, session=session)
    candidates: List[Tuple[str, str]] = []
    for path in root.glob("*.json"):
        if path.name.endswith(".json.bak") or path.is_symlink() or not path.is_file():
            continue
        run_id = path.stem
        try:
            state = load_state(path, path.with_suffix(".json.bak"), WORKFLOW, SCHEMA, run_id, session)
        except WorkflowError:
            continue
        candidates.append((state["updated_at"], run_id))
    if not candidates:
        raise WorkflowError(3, "not_found", "no readable workflow runs exist", workflow=WORKFLOW, session=session)
    candidates.sort()
    return candidates[-1][1]


def common_args(subparser: argparse.ArgumentParser, *, selector: bool = True) -> None:
    if selector:
        subparser.add_argument("--id")
        subparser.add_argument("--latest", action="store_true")
    subparser.add_argument("--session")
    subparser.add_argument("--root")
    subparser.add_argument("--full", action="store_true")


def mutation_args(subparser: argparse.ArgumentParser) -> None:
    common_args(subparser)
    subparser.add_argument("--expected-revision", type=int, required=True)


def response_payload(
    state: Dict[str, Any],
    context: Dict[str, str],
    *,
    full: bool,
    changed: bool,
) -> Dict[str, Any]:
    payload: Dict[str, Any] = {
        "schema": RESPONSE_SCHEMA,
        "ok": True,
        "workflow": WORKFLOW,
        "session": state["session"],
        "id": state["id"],
        "revision": state["revision"],
        "status": state_status(state),
        "stage": state_stage(state),
        "terminal": is_terminal(state),
        "changed": changed,
        "binding": binding_report(state, context, full=full),
        "next_action": next_action(state),
        "metrics": compact_metrics(state),
    }
    if full:
        payload["state"] = state
    return payload


def emit_state(
    state: Dict[str, Any],
    context: Dict[str, str],
    *,
    full: bool,
    changed: bool,
) -> None:
    emit(response_payload(state, context, full=full, changed=changed))


def resolve_artifact_path(
    state: Dict[str, Any],
    raw_path: str,
    *,
    label: str,
    max_bytes: Optional[int] = None,
) -> Tuple[str, Path, Optional[str]]:
    value = bounded_text(raw_path, label, 512)
    worktree = Path(require_dict(state.get("binding"), "binding")["worktree"]).resolve()
    candidate = Path(value).expanduser()
    if not candidate.is_absolute():
        candidate = worktree / candidate
    lexical = Path(os.path.abspath(str(candidate)))
    try:
        lexical_root, lexical_relative = lexical_relative_to_root(lexical, worktree)
    except ValueError as exc:
        raise WorkflowError(2, "unsafe_artifact", "%s escapes the bound worktree" % label, path=value) from exc
    cursor = lexical_root
    for part in lexical_relative.parts:
        cursor = cursor / part
        if cursor.is_symlink():
            raise WorkflowError(2, "unsafe_artifact", "%s traverses a symlink" % label, path=value)
    try:
        resolved = lexical.resolve(strict=True)
    except (OSError, RuntimeError) as exc:
        raise WorkflowError(2, "invalid_artifact", "%s does not exist" % label, path=value) from exc
    try:
        relative = resolved.relative_to(worktree)
    except ValueError as exc:
        raise WorkflowError(2, "unsafe_artifact", "%s escapes the bound worktree" % label, path=value) from exc
    if not resolved.is_file():
        raise WorkflowError(2, "invalid_artifact", "%s must be a regular file" % label, path=value)
    content: Optional[str] = None
    if max_bytes is not None:
        size = resolved.stat().st_size
        if size > max_bytes:
            raise WorkflowError(2, "artifact_too_large", "%s exceeds its size limit" % label, path=value, limit=max_bytes)
        try:
            content = resolved.read_text(encoding="utf-8")
        except (OSError, UnicodeError) as exc:
            raise WorkflowError(2, "invalid_artifact", "%s must be readable UTF-8 text" % label, path=value) from exc
    return relative.as_posix(), resolved, content


def command_status(args: argparse.Namespace) -> int:
    context = workspace_context(args.root)
    session = normalize_session(args.session)
    run_id = resolve_run_id(args, context, session)
    path, backup, _ = state_paths(context, WORKFLOW, session, run_id, create=False)
    state = load_state(path, backup, WORKFLOW, SCHEMA, run_id, session)
    emit_state(state, context, full=args.full, changed=False)
    return 0


def command_list(args: argparse.Namespace) -> int:
    context = workspace_context(args.root)
    sessions: List[str]
    requested = normalize_session(args.session)
    base = Path(context["repository_root"]) / STATE_ROOT_NAME / WORKFLOW
    if args.limit < 1 or args.limit > MAX_LIST_LIMIT:
        raise WorkflowError(2, "invalid_limit", "--limit must be between 1 and %d" % MAX_LIST_LIMIT)
    if args.all_sessions and base.is_dir() and not base.is_symlink():
        sessions = sorted(path.name for path in base.iterdir() if path.is_dir() and not path.is_symlink())
    else:
        sessions = [requested]
    runs: List[Dict[str, Any]] = []
    for session in sessions:
        root = workflow_root(context, WORKFLOW, session, create=False)
        if not root.is_dir():
            continue
        for path in sorted(root.glob("*.json")):
            if path.name.endswith(".json.bak") or path.is_symlink() or not path.is_file():
                continue
            run_id = path.stem
            entry: Dict[str, Any] = {"session": session, "id": run_id}
            try:
                state = load_state(path, path.with_suffix(".json.bak"), WORKFLOW, SCHEMA, run_id, session)
                entry.update(
                    {
                        "revision": state["revision"],
                        "status": state_status(state),
                        "stage": state_stage(state),
                        "terminal": is_terminal(state),
                        "updated_at": state["updated_at"],
                    }
                )
            except WorkflowError as exc:
                entry.update({"health": exc.kind})
            runs.append(entry)
    runs.sort(
        key=lambda row: (row.get("updated_at", ""), row.get("session", ""), row.get("id", "")),
        reverse=True,
    )
    total = len(runs)
    runs = runs[: args.limit]
    emit(
        {
            "schema": RESPONSE_SCHEMA,
            "ok": True,
            "workflow": WORKFLOW,
            "total": total,
            "count": len(runs),
            "truncated": total > len(runs),
            "limit": args.limit,
            "runs": runs,
        }
    )
    return 0


def command_history(args: argparse.Namespace) -> int:
    if args.tail < 1 or args.tail > MAX_HISTORY_TAIL:
        raise WorkflowError(2, "invalid_tail", "--tail must be between 1 and %d" % MAX_HISTORY_TAIL)
    context = workspace_context(args.root)
    session = normalize_session(args.session)
    run_id = resolve_run_id(args, context, session)
    path, backup, _ = state_paths(context, WORKFLOW, session, run_id, create=False)
    state = load_state(path, backup, WORKFLOW, SCHEMA, run_id, session)
    rows = history_rows(state, full=args.full)[-args.tail :]
    emit(
        {
            "schema": RESPONSE_SCHEMA,
            "ok": True,
            "workflow": WORKFLOW,
            "session": session,
            "id": run_id,
            "revision": state["revision"],
            "tail": len(rows),
            "history": rows,
        }
    )
    return 0


def command_doctor(args: argparse.Namespace) -> int:
    context = workspace_context(args.root)
    session = normalize_session(args.session)
    run_id = resolve_run_id(args, context, session)
    path, backup, lock = state_paths(context, WORKFLOW, session, run_id, create=False)
    health: Dict[str, Any] = {
        "primary": {"exists": path.exists(), "valid": False, "path": str(path)},
        "backup": {"exists": backup.exists(), "valid": False, "path": str(backup)},
        "lock": lock_details(lock),
    }
    state: Optional[Dict[str, Any]] = None
    if path.exists():
        try:
            state = load_state(path, backup, WORKFLOW, SCHEMA, run_id, session)
            health["primary"]["valid"] = True
        except WorkflowError as exc:
            health["primary"]["error"] = exc.kind
    if backup.exists() and backup.is_file() and not backup.is_symlink():
        try:
            backup_state = read_json(backup, kind="corrupt_state", max_bytes=MAX_STATE_BYTES)
            validate_common_state(
                backup_state,
                workflow=WORKFLOW,
                schema=SCHEMA,
                run_id=run_id,
                session=session,
                path=backup,
            )
            health["backup"]["valid"] = True
        except WorkflowError as exc:
            health["backup"]["error"] = exc.kind
    lock_health = health["lock"]
    healthy = bool(
        health["primary"]["valid"]
        and lock_health.get("safe", True)
        and not lock_health.get("exists", False)
    )
    payload: Dict[str, Any] = {
        "schema": RESPONSE_SCHEMA,
        "ok": healthy,
        "workflow": WORKFLOW,
        "session": session,
        "id": run_id,
        "health": health,
    }
    if state is not None:
        payload.update(
            {
                "revision": state["revision"],
                "status": state_status(state),
                "stage": state_stage(state),
                "terminal": is_terminal(state),
            }
        )
    emit(payload, stream=sys.stdout if healthy else sys.stderr)
    return 0 if healthy else 6


def command_recover(args: argparse.Namespace) -> int:
    context = workspace_context(args.root)
    session = normalize_session(args.session)
    run_id = resolve_run_id(args, context, session)
    path, backup, lock = state_paths(context, WORKFLOW, session, run_id, create=False)
    if not backup.exists() or backup.is_symlink() or not backup.is_file():
        raise WorkflowError(6, "backup_not_found", "no safe backup is available", backup=str(backup))
    with command_lock(lock):
        primary_valid = False
        primary_revision = 0
        if path.exists():
            try:
                primary_state = load_state(path, backup, WORKFLOW, SCHEMA, run_id, session)
                primary_valid = True
                primary_revision = primary_state["revision"]
            except WorkflowError:
                primary_valid = False
                try:
                    raw_primary = read_json(path, kind="corrupt_state", max_bytes=MAX_STATE_BYTES)
                    raw_revision = raw_primary.get("revision")
                    if isinstance(raw_revision, int) and not isinstance(raw_revision, bool) and raw_revision > 0:
                        primary_revision = raw_revision
                except WorkflowError:
                    primary_revision = 0
        if primary_valid and not args.force:
            raise WorkflowError(5, "recovery_not_needed", "primary state is valid; use --force only for an intentional rollback")
        state = read_json(backup, kind="corrupt_state", max_bytes=MAX_STATE_BYTES)
        validate_common_state(
            state,
            workflow=WORKFLOW,
            schema=SCHEMA,
            run_id=run_id,
            session=session,
            path=backup,
        )
        report = binding_report(state, context, full=True)
        if not report["ok"] and not args.rebind:
            raise WorkflowError(
                5,
                "binding_mismatch",
                "backup is owned by another worktree or branch; rerun with --rebind only after confirming transfer",
                binding=report,
            )
        if args.rebind:
            state["binding"] = new_binding(context)
        state["revision"] = max(state["revision"], primary_revision) + 1
        recoveries = state["recoveries"]
        recoveries.append(
            {"at": now(), "source": "backup", "forced": bool(args.force), "rebound": bool(args.rebind)}
        )
        if len(recoveries) > 20:
            del recoveries[:-20]
        state["updated_at"] = now()
        validate_common_state(
            state,
            workflow=WORKFLOW,
            schema=SCHEMA,
            run_id=run_id,
            session=session,
            path=path,
        )
        payload = (
            json.dumps(state, ensure_ascii=False, indent=2, sort_keys=True, allow_nan=False) + "\n"
        ).encode("utf-8")
        atomic_write(path, payload)
    emit_state(state, context, full=args.full, changed=True)
    return 0


def command_unlock(args: argparse.Namespace) -> int:
    if args.stale_after < 0:
        raise WorkflowError(2, "invalid_bounds", "--stale-after must be zero or greater")
    context = workspace_context(args.root)
    session = normalize_session(args.session)
    run_id = resolve_run_id(args, context, session)
    _, _, lock = state_paths(context, WORKFLOW, session, run_id, create=False)
    details = lock_details(lock)
    if not details["exists"]:
        emit(
            {
                "schema": RESPONSE_SCHEMA,
                "ok": True,
                "workflow": WORKFLOW,
                "session": session,
                "id": run_id,
                "changed": False,
                "lock": details,
            }
        )
        return 0
    if lock.is_symlink() or not lock.is_file():
        raise WorkflowError(6, "unsafe_lock_file", "lock path is unsafe", path=str(lock))
    if details.get("alive") and not args.force:
        raise WorkflowError(5, "lock_owner_alive", "lock owner is still alive", lock=details)
    age = details.get("age_seconds")
    if not args.force and (age is None or age < args.stale_after):
        raise WorkflowError(5, "lock_not_stale", "lock is not old enough to remove", lock=details, stale_after=args.stale_after)
    before_owner = details.get("owner") or {}
    current = lock_details(lock)
    current_owner = current.get("owner") or {}
    before_identity = (before_owner.get("token"), before_owner.get("pid"), before_owner.get("created_at"))
    current_identity = (current_owner.get("token"), current_owner.get("pid"), current_owner.get("created_at"))
    if not current.get("exists") or current_identity != before_identity:
        raise WorkflowError(5, "lock_changed", "lock ownership changed during unlock; retry after rechecking", lock=current)
    lock.unlink()
    emit(
        {
            "schema": RESPONSE_SCHEMA,
            "ok": True,
            "workflow": WORKFLOW,
            "session": session,
            "id": run_id,
            "changed": True,
            "removed_lock": str(lock),
        }
    )
    return 0


def command_rebind(args: argparse.Namespace) -> int:
    context = workspace_context(args.root)
    session = normalize_session(args.session)
    run_id = resolve_run_id(args, context, session)
    path, backup, lock = state_paths(context, WORKFLOW, session, run_id, create=False)
    with command_lock(lock):
        state = require_mutable(
            path,
            backup,
            run_id,
            session,
            args.expected_revision,
            context,
            allow_mismatch=True,
        )
        if is_terminal(state):
            raise WorkflowError(4, "terminal", "terminal runs cannot be rebound", status=state_status(state))
        state["binding"] = new_binding(context)
        bump(state)
        save_state(path, backup, state)
    emit_state(state, context, full=args.full, changed=True)
    return 0


def add_common_commands(sub: Any) -> None:
    parser = sub.add_parser("status")
    common_args(parser)
    parser.set_defaults(func=command_status)

    parser = sub.add_parser("list")
    common_args(parser, selector=False)
    parser.add_argument("--all-sessions", action="store_true")
    parser.add_argument("--limit", type=int, default=DEFAULT_LIST_LIMIT)
    parser.set_defaults(func=command_list)

    parser = sub.add_parser("history")
    common_args(parser)
    parser.add_argument("--tail", type=int, default=DEFAULT_HISTORY_TAIL)
    parser.set_defaults(func=command_history)

    parser = sub.add_parser("doctor")
    common_args(parser)
    parser.set_defaults(func=command_doctor)

    parser = sub.add_parser("recover")
    common_args(parser)
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--rebind", action="store_true")
    parser.set_defaults(func=command_recover)

    parser = sub.add_parser("unlock")
    common_args(parser)
    parser.add_argument("--stale-after", type=int, default=300)
    parser.add_argument("--force", action="store_true")
    parser.set_defaults(func=command_unlock)

    parser = sub.add_parser("rebind")
    mutation_args(parser)
    parser.set_defaults(func=command_rebind)


def error_payload(exc: WorkflowError) -> Dict[str, Any]:
    return {
        "schema": RESPONSE_SCHEMA,
        "ok": False,
        "workflow": globals().get("WORKFLOW", "unknown"),
        "error": exc.kind,
        "message": exc.message,
        "details": exc.details,
    }


def run_main(parser_factory: Any, argv: Optional[List[str]] = None) -> int:
    configure_streams()
    try:
        args = parser_factory().parse_args(argv)
        return int(args.func(args))
    except WorkflowError as exc:
        emit(error_payload(exc), stream=sys.stderr)
        return exc.code
    except Exception as exc:  # fail closed without leaking a traceback into agent context
        if os.environ.get("AGENT_WORKFLOW_DEBUG") == "1":
            traceback.print_exc(file=sys.stderr)
        emit(
            {
                "schema": RESPONSE_SCHEMA,
                "ok": False,
                "workflow": globals().get("WORKFLOW", "unknown"),
                "error": "internal_error",
                "message": "unexpected runtime failure; run doctor or set AGENT_WORKFLOW_DEBUG=1 locally",
                "details": {"exception": type(exc).__name__},
            },
            stream=sys.stderr,
        )
        return 70


WORKFLOW = "ralph"
SCHEMA = "agent-workflow/ralph/2"
TERMINAL_STATUSES = {"passed", "stalled", "plateaued", "exhausted", "aborted"}
KEEP_POLICIES = {"pass_only", "score_improvement"}
PROFILES = {"standard", "research", "adversarial-qa"}


def normalize_keep_policy(value: str) -> str:
    mapping = {
        "pass": "pass_only",
        "pass-only": "pass_only",
        "pass_only": "pass_only",
        "score-improvement": "score_improvement",
        "score_improvement": "score_improvement",
    }
    return mapping[value]


def validate_workflow_state(state: Dict[str, Any]) -> None:
    status = require_str(state.get("status"), "status")
    if status not in {"active", *TERMINAL_STATUSES}:
        raise WorkflowError(6, "corrupt_state", "ralph status is invalid")
    goal = require_str(state.get("goal"), "goal")
    if len(goal) > 2000:
        raise WorkflowError(6, "corrupt_state", "goal exceeds its bounded length")
    profile = require_str(state.get("profile"), "profile")
    policy = require_str(state.get("keep_policy"), "keep_policy")
    if profile not in PROFILES or policy not in KEEP_POLICIES:
        raise WorkflowError(6, "corrupt_state", "ralph profile or keep policy is invalid")
    max_rounds = require_int(state.get("max_rounds"), "max_rounds", minimum=1)
    if max_rounds > 50:
        raise WorkflowError(6, "corrupt_state", "max_rounds exceeds 50")
    round_value = require_int(state.get("round"), "round", minimum=0)
    if round_value > max_rounds:
        raise WorkflowError(6, "corrupt_state", "round exceeds max_rounds")
    pending = state.get("pending_round")
    if pending is not None and (isinstance(pending, bool) or not isinstance(pending, int) or pending != round_value):
        raise WorkflowError(6, "corrupt_state", "pending_round must match the current round")
    stall_window = require_int(state.get("stall_window"), "stall_window", minimum=2)
    plateau_window = require_int(state.get("plateau_window"), "plateau_window", minimum=2)
    if stall_window > 10 or plateau_window > 10:
        raise WorkflowError(6, "corrupt_state", "ralph windows exceed 10")
    best_score = require_number(state.get("best_score"), "best_score", nullable=True)
    if best_score is not None and not 0.0 <= best_score <= 1.0:
        raise WorkflowError(6, "corrupt_state", "best_score must be between 0 and 1")
    best_round = state.get("best_round")
    if best_round is not None:
        require_int(best_round, "best_round", minimum=1)
        if best_round > round_value:
            raise WorkflowError(6, "corrupt_state", "best_round exceeds the current round")
    require_int(state.get("no_improvement"), "no_improvement", minimum=0)
    history = require_list(state.get("history"), "history")
    if len(history) > max_rounds or len(history) > 50:
        raise WorkflowError(6, "corrupt_state", "ralph history exceeds its round budget")
    seen: List[int] = []
    for index, value in enumerate(history):
        row = require_dict(value, "history[%d]" % index)
        row_round = require_int(row.get("round"), "history[%d].round" % index, minimum=1)
        seen.append(row_round)
        exit_code = require_int(row.get("verifier_exit"), "history[%d].verifier_exit" % index, minimum=0)
        if exit_code > 255:
            raise WorkflowError(6, "corrupt_state", "verifier exit code exceeds 255")
        signature = require_str(row.get("signature"), "history[%d].signature" % index, allow_empty=True)
        note = require_str(row.get("note"), "history[%d].note" % index, allow_empty=True)
        if len(signature) > 500 or len(note) > 2000:
            raise WorkflowError(6, "corrupt_state", "ralph history text exceeds its limit")
        score = require_number(row.get("score"), "history[%d].score" % index, nullable=True)
        if score is not None and not 0.0 <= score <= 1.0:
            raise WorkflowError(6, "corrupt_state", "ralph score must be between 0 and 1")
        if not isinstance(row.get("improved"), bool):
            raise WorkflowError(6, "corrupt_state", "history improved flag must be boolean")
        require_timestamp(row.get("recorded_at"), "history[%d].recorded_at" % index)
    if seen != list(range(1, len(seen) + 1)):
        raise WorkflowError(6, "corrupt_state", "ralph history rounds must be consecutive")
    if round_value != len(history) + (1 if pending is not None else 0):
        raise WorkflowError(6, "corrupt_state", "round, history, and pending_round are inconsistent")
    if pending is not None and status != "active":
        raise WorkflowError(6, "corrupt_state", "only an active ralph run can have a pending round")
    passing_rows = [row for row in history if row["verifier_exit"] == 0]
    if len(passing_rows) > 1 or (passing_rows and history[-1]["verifier_exit"] != 0):
        raise WorkflowError(6, "corrupt_state", "verifier pass ordering is inconsistent")
    if policy == "pass_only":
        if best_score is not None or best_round is not None or state["no_improvement"] != 0:
            raise WorkflowError(6, "corrupt_state", "pass-only state cannot contain score-improvement metrics")
        if any(row["score"] is not None or row["improved"] for row in history):
            raise WorkflowError(6, "corrupt_state", "pass-only history cannot contain scores")
    else:
        if any(row["score"] is None for row in history):
            raise WorkflowError(6, "corrupt_state", "score-improvement history requires a score per round")
        if history:
            expected_best = max(float(row["score"]) for row in history)
            expected_round = next(row["round"] for row in history if float(row["score"]) == expected_best)
            if best_score != expected_best or best_round != expected_round:
                raise WorkflowError(6, "corrupt_state", "best score metadata does not match history")
        elif best_score is not None or best_round is not None:
            raise WorkflowError(6, "corrupt_state", "empty score history cannot have a best score")
    if status in TERMINAL_STATUSES and pending is not None:
        raise WorkflowError(6, "corrupt_state", "terminal ralph run cannot have a pending round")
    if status == "passed" and (not history or history[-1]["verifier_exit"] != 0):
        raise WorkflowError(6, "corrupt_state", "passed ralph run requires a successful final verifier")
    if status == "exhausted" and round_value != max_rounds:
        raise WorkflowError(6, "corrupt_state", "exhausted ralph run must consume its round budget")
    if status == "stalled" and (not history or consecutive_signature(history, history[-1]["signature"]) < stall_window):
        raise WorkflowError(6, "corrupt_state", "stalled ralph run lacks the required repeated signature")
    if status == "plateaued" and state["no_improvement"] < plateau_window:
        raise WorkflowError(6, "corrupt_state", "plateaued ralph run lacks the required non-improvement window")
    terminal_reason = state.get("terminal_reason")
    if terminal_reason is not None and (not isinstance(terminal_reason, str) or not terminal_reason or len(terminal_reason) > 1000):
        raise WorkflowError(6, "corrupt_state", "terminal_reason must be null or bounded text")
    if status == "active" and terminal_reason is not None:
        raise WorkflowError(6, "corrupt_state", "active ralph run cannot have a terminal reason")
    if status in TERMINAL_STATUSES and terminal_reason is None:
        raise WorkflowError(6, "corrupt_state", "terminal ralph run requires a reason")


def state_status(state: Dict[str, Any]) -> str:
    return state["status"]


def state_stage(state: Dict[str, Any]) -> str:
    return "round_pending" if state["pending_round"] is not None else state["status"]


def is_terminal(state: Dict[str, Any]) -> bool:
    return state["status"] in TERMINAL_STATUSES


def next_action(state: Dict[str, Any]) -> str:
    if state["status"] == "active" and state["pending_round"] is None:
        return "open the next round"
    if state["status"] == "active":
        return "make one bounded attempt, run the verifier, then submit check"
    return "stop and report the terminal judgment"


def compact_metrics(state: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "round": state["round"],
        "max_rounds": state["max_rounds"],
        "pending_round": state["pending_round"],
        "keep_policy": state["keep_policy"],
        "best_score": state["best_score"],
        "best_round": state["best_round"],
        "last_signature": state["history"][-1]["signature"] if state["history"] else "",
        "terminal_reason": state["terminal_reason"],
    }


def history_rows(state: Dict[str, Any], *, full: bool) -> List[Dict[str, Any]]:
    if full:
        return list(state["history"])
    return [
        {
            "round": row["round"],
            "verifier_exit": row["verifier_exit"],
            "signature": row["signature"][:160],
            "score": row["score"],
            "improved": row["improved"],
            "recorded_at": row["recorded_at"],
        }
        for row in state["history"]
    ]


def command_start(args: argparse.Namespace) -> int:
    if not 1 <= args.max_rounds <= 50:
        raise WorkflowError(2, "invalid_bounds", "--max-rounds must be between 1 and 50")
    if not 2 <= args.stall_window <= 10 or not 2 <= args.plateau_window <= 10:
        raise WorkflowError(2, "invalid_bounds", "stall and plateau windows must be between 2 and 10")
    context = workspace_context(args.root)
    session = normalize_session(args.session)
    run_id = validate_id(args.id) if args.id else "default"
    goal = bounded_text(args.goal, "goal", 2000)
    keep_policy = normalize_keep_policy(args.keep_policy)
    path, backup, lock = state_paths(context, WORKFLOW, session, run_id, create=True)
    with command_lock(lock):
        if path.exists():
            existing = load_state(path, backup, WORKFLOW, SCHEMA, run_id, session)
            raise WorkflowError(
                5,
                "already_exists",
                "ralph run already exists",
                revision=existing["revision"],
                status=existing["status"],
            )
        stamp = now()
        state: Dict[str, Any] = {
            "schema": SCHEMA,
            "workflow": WORKFLOW,
            "id": run_id,
            "session": session,
            "revision": 1,
            "status": "active",
            "goal": goal,
            "profile": args.profile,
            "keep_policy": keep_policy,
            "max_rounds": args.max_rounds,
            "stall_window": args.stall_window,
            "plateau_window": args.plateau_window,
            "round": 0,
            "pending_round": None,
            "history": [],
            "best_score": None,
            "best_round": None,
            "no_improvement": 0,
            "terminal_reason": None,
            "binding": new_binding(context),
            "recoveries": [],
            "created_at": stamp,
            "updated_at": stamp,
        }
        save_state(path, backup, state)
    emit_state(state, context, full=args.full, changed=True)
    return 0


def command_next(args: argparse.Namespace) -> int:
    context = workspace_context(args.root)
    session = normalize_session(args.session)
    run_id = resolve_run_id(args, context, session)
    path, backup, lock = state_paths(context, WORKFLOW, session, run_id, create=False)
    with command_lock(lock):
        state = require_mutable(path, backup, run_id, session, args.expected_revision, context)
        if is_terminal(state):
            raise WorkflowError(4, "terminal", "ralph run is terminal", status=state["status"], reason=state["terminal_reason"])
        if state["pending_round"] is not None:
            raise WorkflowError(5, "round_pending", "submit the pending round before opening another", round=state["pending_round"])
        if state["round"] >= state["max_rounds"]:
            state["status"] = "exhausted"
            state["terminal_reason"] = "round budget exhausted"
        else:
            state["round"] += 1
            state["pending_round"] = state["round"]
        bump(state)
        save_state(path, backup, state)
    emit_state(state, context, full=args.full, changed=True)
    return 0


def consecutive_signature(history: List[Dict[str, Any]], signature: str) -> int:
    count = 0
    for row in reversed(history):
        if row["verifier_exit"] == 0 or row["signature"] != signature:
            break
        count += 1
    return count


def command_check(args: argparse.Namespace) -> int:
    if args.verifier_exit < 0 or args.verifier_exit > 255:
        raise WorkflowError(2, "invalid_exit_code", "verifier exit must be between 0 and 255")
    signature = bounded_text(args.signature, "signature", 500, allow_empty=True)
    note = bounded_text(args.note, "note", 2000, allow_empty=True)
    context = workspace_context(args.root)
    session = normalize_session(args.session)
    run_id = resolve_run_id(args, context, session)
    path, backup, lock = state_paths(context, WORKFLOW, session, run_id, create=False)
    with command_lock(lock):
        state = require_mutable(path, backup, run_id, session, args.expected_revision, context)
        if is_terminal(state):
            raise WorkflowError(4, "terminal", "ralph run is terminal", status=state["status"])
        if state["pending_round"] != args.round:
            raise WorkflowError(
                5,
                "round_mismatch",
                "result must match the single pending round",
                pending=state["pending_round"],
                submitted=args.round,
            )
        if args.verifier_exit != 0 and not signature:
            raise WorkflowError(2, "invalid_signature", "a failing verifier needs a stable non-empty signature")
        if state["keep_policy"] == "score_improvement":
            if args.score is None or not math.isfinite(args.score) or not 0.0 <= args.score <= 1.0:
                raise WorkflowError(2, "invalid_score", "score-improvement runs require --score between 0 and 1")
        elif args.score is not None:
            raise WorkflowError(2, "unexpected_score", "--score is valid only for score-improvement runs")

        improved = False
        if state["keep_policy"] == "score_improvement":
            improved = state["best_score"] is None or args.score > state["best_score"]
        row = {
            "round": args.round,
            "verifier_exit": args.verifier_exit,
            "signature": signature,
            "score": args.score,
            "improved": improved,
            "note": note,
            "recorded_at": now(),
        }
        state["history"].append(row)
        state["pending_round"] = None

        if args.verifier_exit == 0:
            if improved:
                state["best_score"] = args.score
                state["best_round"] = args.round
            state["status"] = "passed"
            state["terminal_reason"] = "verifier passed"
        elif state["keep_policy"] == "pass_only":
            repeated = consecutive_signature(state["history"], signature)
            if repeated >= state["stall_window"]:
                state["status"] = "stalled"
                state["terminal_reason"] = "signature repeated %d rounds: %s" % (repeated, signature)
            elif state["round"] >= state["max_rounds"]:
                state["status"] = "exhausted"
                state["terminal_reason"] = "round budget exhausted"
        else:
            if improved:
                state["best_score"] = args.score
                state["best_round"] = args.round
                state["no_improvement"] = 0
            else:
                state["no_improvement"] += 1
            if state["no_improvement"] >= state["plateau_window"]:
                state["status"] = "plateaued"
                state["terminal_reason"] = "score did not improve for %d rounds" % state["no_improvement"]
            elif state["round"] >= state["max_rounds"]:
                state["status"] = "exhausted"
                state["terminal_reason"] = "round budget exhausted"

        bump(state)
        save_state(path, backup, state)
    emit_state(state, context, full=args.full, changed=True)
    return 0


def command_abort(args: argparse.Namespace) -> int:
    reason = bounded_text(args.reason, "reason", 1000)
    context = workspace_context(args.root)
    session = normalize_session(args.session)
    run_id = resolve_run_id(args, context, session)
    path, backup, lock = state_paths(context, WORKFLOW, session, run_id, create=False)
    with command_lock(lock):
        state = require_mutable(path, backup, run_id, session, args.expected_revision, context)
        if is_terminal(state):
            raise WorkflowError(4, "terminal", "ralph run is already terminal", status=state["status"])
        state["status"] = "aborted"
        state["terminal_reason"] = reason
        state["pending_round"] = None
        bump(state)
        save_state(path, backup, state)
    emit_state(state, context, full=args.full, changed=True)
    return 0


def parser() -> JsonArgumentParser:
    root = JsonArgumentParser(description="Deterministic bounded verifier loop")
    sub = root.add_subparsers(dest="command", required=True)

    command = sub.add_parser("start")
    command.add_argument("--id")
    common_args(command, selector=False)
    command.add_argument("--goal", required=True)
    command.add_argument("--max-rounds", type=int, default=10)
    command.add_argument("--stall-window", type=int, default=3)
    command.add_argument("--plateau-window", type=int, default=3)
    command.add_argument(
        "--keep-policy",
        choices=["pass", "pass-only", "pass_only", "score-improvement", "score_improvement"],
        default="pass-only",
    )
    command.add_argument("--profile", choices=sorted(PROFILES), default="standard")
    command.set_defaults(func=command_start)

    command = sub.add_parser("next")
    mutation_args(command)
    command.set_defaults(func=command_next)

    command = sub.add_parser("check")
    mutation_args(command)
    command.add_argument("--round", type=int, required=True)
    command.add_argument("--verifier-exit", type=int, required=True)
    command.add_argument("--signature", default="")
    command.add_argument("--score", type=float)
    command.add_argument("--note", default="")
    command.set_defaults(func=command_check)

    command = sub.add_parser("abort")
    mutation_args(command)
    command.add_argument("--reason", required=True)
    command.set_defaults(func=command_abort)

    add_common_commands(sub)
    return root


if __name__ == "__main__":
    raise SystemExit(run_main(parser))
