# Generated by scripts/generate_p0_runtimes.py; do not edit.
from __future__ import annotations

import argparse
import fnmatch
import getpass
import hashlib
import json
import os
import re
import secrets
import shutil
import stat
import sys
import time
from pathlib import Path, PurePosixPath
from typing import Any, Callable, Dict, Iterable, List, Mapping, MutableMapping, Optional, Sequence, Tuple

from .common import (
    FileMutex,
    GitContext,
    HarnessError,
    SCHEMA_VERSION,
    append_bytes_fsync,
    canonical_json,
    digest_json,
    discover_git_context,
    ensure_relative_path,
    fsync_dir,
    patterns_overlap,
    match_any,
    read_json,
    run_git,
    safe_child,
    utc_now,
    validate_identifier,
    write_json_atomic,
)

EXIT_OK = 0
EXIT_USAGE = 2
EXIT_DATA = 3
EXIT_CONFLICT = 10
EXIT_LEASE = 11
EXIT_STATE = 12
EXIT_WORKSPACE = 13
EXIT_VERIFY = 14
CONTRACT = "agent-work/v1"
RUNTIME_DIR_NAME = "agent-work-v1"
TASK_REL_ROOT = ".agents/work"
PHASES = {"clarifying", "planned", "executing", "verifying", "done", "blocked", "cancelled"}
BUILTIN_OWNERS = {"native", "autopilot", "ralph", "pairroom"}
WORKSPACE_ROLES = {"driver", "worker", "reviewer", "integrator"}
WRITABLE_ROLES = {"driver", "worker", "integrator"}
TRANSITIONS = {
    "clarifying": {"planned", "blocked", "cancelled"},
    "planned": {"executing", "blocked", "cancelled"},
    "executing": {"verifying", "blocked", "cancelled"},
    "verifying": {"done", "executing", "blocked", "cancelled"},
    "blocked": {"clarifying", "planned", "executing", "verifying", "cancelled"},
    "done": set(),
    "cancelled": set(),
}
FULL_COMMIT_RE = re.compile(r"^(?:[0-9a-fA-F]{40}|[0-9a-fA-F]{64})$")
CUSTOM_OWNER_RE = re.compile(r"^custom:[a-z0-9][a-z0-9._-]{0,63}$")
MAX_ARTIFACT_BYTES = 256 * 1024
BRIEF_SECTIONS = ("Goal", "Non-goals", "Acceptance criteria", "Authority and external effects")
PLAN_SECTIONS = ("Slices", "Risks and dependencies", "Ownership")
VERIFICATION_EVIDENCE_KINDS = {"test", "verify", "verification", "ci", "quality-gate"}


def _need_dict(value: Any, label: str) -> Dict[str, Any]:
    if not isinstance(value, dict):
        raise HarnessError("%s must be an object" % label, code=EXIT_DATA)
    return value


def _need_int(value: Any, label: str, minimum: int = 0) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or value < minimum:
        raise HarnessError("%s must be an integer >= %d" % (label, minimum), code=EXIT_DATA)
    return value


def validate_owner(owner: str) -> str:
    if owner in BUILTIN_OWNERS or CUSTOM_OWNER_RE.fullmatch(owner or ""):
        return owner
    raise HarnessError(
        "loop owner must be native, autopilot, ralph, pairroom, or custom:<slug>",
        code=EXIT_DATA,
    )


def token_hash(token: str) -> str:
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def _token_from_args(args: argparse.Namespace, required: bool = True) -> Optional[str]:
    values = []
    direct = getattr(args, "token", None)
    if direct:
        values.append(direct)
    token_file = getattr(args, "token_file", None)
    if token_file:
        try:
            values.append(Path(token_file).read_text(encoding="utf-8").strip())
        except OSError as exc:
            raise HarnessError("cannot read token file: %s" % exc, code=EXIT_LEASE) from exc
    env_token = os.environ.get("WORKCTL_LEASE_TOKEN")
    if env_token:
        values.append(env_token)
    values = [value for value in values if value]
    if len(values) > 1 and len(set(values)) > 1:
        raise HarnessError("conflicting lease token sources", code=EXIT_LEASE)
    if any(len(value) > 1024 or "\x00" in value for value in values):
        raise HarnessError("lease token is malformed", code=EXIT_LEASE)
    if not values:
        if required:
            raise HarnessError("lease token required via --token, --token-file, or WORKCTL_LEASE_TOKEN", code=EXIT_LEASE)
        return None
    return values[0]


def _hash_event(event_without_hash: Mapping[str, Any]) -> str:
    return hashlib.sha256(canonical_json(event_without_hash)).hexdigest()


def _read_evidence(path: Path, task_id: str, max_bytes: int = 64 * 1024 * 1024) -> Tuple[List[Dict[str, Any]], str]:
    if not path.exists():
        return [], "0" * 64
    if path.stat().st_size > max_bytes:
        raise HarnessError("evidence log exceeds safety limit", code=EXIT_VERIFY)
    events: List[Dict[str, Any]] = []
    previous = "0" * 64
    try:
        with path.open("r", encoding="utf-8", newline="") as handle:
            for number, line in enumerate(handle, 1):
                if not line.endswith("\n"):
                    raise HarnessError("evidence log has a truncated final line", code=EXIT_VERIFY)
                try:
                    event = json.loads(line)
                except json.JSONDecodeError as exc:
                    raise HarnessError("invalid evidence JSON at line %d" % number, code=EXIT_VERIFY) from exc
                if not isinstance(event, dict):
                    raise HarnessError("evidence line %d is not an object" % number, code=EXIT_VERIFY)
                if event.get("schema_version") != SCHEMA_VERSION or event.get("contract") != CONTRACT:
                    raise HarnessError("evidence contract mismatch at line %d" % number, code=EXIT_VERIFY)
                if event.get("task_id") != task_id or event.get("seq") != number:
                    raise HarnessError("evidence identity/sequence mismatch at line %d" % number, code=EXIT_VERIFY)
                if event.get("prev_hash") != previous:
                    raise HarnessError("evidence hash chain mismatch at line %d" % number, code=EXIT_VERIFY)
                supplied = event.get("hash")
                base = dict(event)
                base.pop("hash", None)
                expected = _hash_event(base)
                if not isinstance(supplied, str) or not secrets.compare_digest(supplied, expected):
                    raise HarnessError("evidence hash mismatch at line %d" % number, code=EXIT_VERIFY)
                previous = supplied
                events.append(event)
    except UnicodeError as exc:
        raise HarnessError("evidence log is not UTF-8", code=EXIT_VERIFY) from exc
    return events, previous


def _make_event(path: Path, task_id: str, kind: str, actor: str, payload: Mapping[str, Any]) -> Dict[str, Any]:
    events, previous = _read_evidence(path, task_id)
    event: Dict[str, Any] = {
        "schema_version": SCHEMA_VERSION,
        "contract": CONTRACT,
        "task_id": task_id,
        "seq": len(events) + 1,
        "timestamp": utc_now(),
        "kind": validate_identifier(kind, "evidence kind"),
        "actor": actor[:128],
        "payload": dict(payload),
        "prev_hash": previous,
    }
    event["hash"] = _hash_event(event)
    return event


def _append_event(path: Path, event: Mapping[str, Any], task_id: str) -> None:
    events, previous = _read_evidence(path, task_id)
    if event.get("seq") != len(events) + 1 or event.get("prev_hash") != previous:
        raise HarnessError("evidence event no longer follows the current chain", code=EXIT_CONFLICT)
    base = dict(event)
    supplied = base.pop("hash", None)
    if supplied != _hash_event(base):
        raise HarnessError("prepared evidence event hash is invalid", code=EXIT_VERIFY)
    append_bytes_fsync(path, canonical_json(event) + b"\n", mode=0o644)


class TaskStore:
    def __init__(self, context: GitContext, task_id: str):
        self.context = context
        self.task_id = validate_identifier(task_id, "task id")
        self.runtime = context.common_dir / RUNTIME_DIR_NAME
        self.registry_path = self.runtime / "tasks" / (self.task_id + ".json")
        self.lock_path = self.runtime / "locks" / (self.task_id + ".lock")
        self.txn_path = self.runtime / "transactions" / (self.task_id + ".json")

    @staticmethod
    def for_existing(start: Path, task_id: str) -> "TaskStore":
        context = discover_git_context(start)
        store = TaskStore(context, task_id)
        if not store.registry_path.exists():
            raise HarnessError("unknown task: %s" % task_id, code=EXIT_DATA)
        return store

    def _read_registry(self) -> Dict[str, Any]:
        registry = _need_dict(read_json(self.registry_path), "task registry")
        if registry.get("schema_version") != SCHEMA_VERSION or registry.get("contract") != CONTRACT:
            raise HarnessError("task registry schema mismatch", code=EXIT_VERIFY)
        if registry.get("task_id") != self.task_id:
            raise HarnessError("task registry identity mismatch", code=EXIT_VERIFY)
        _need_int(registry.get("version"), "registry.version", 1)
        _need_int(registry.get("state_version", 1), "registry.state_version", 1)
        authority_raw = registry.get("authority_root")
        if not isinstance(authority_raw, str) or not authority_raw:
            raise HarnessError("task registry has no authority root", code=EXIT_VERIFY)
        authority = Path(authority_raw)
        if not authority.is_absolute():
            raise HarnessError("local task registry authority must be absolute", code=EXIT_VERIFY)
        return registry

    def authority_root(self, registry: Optional[Mapping[str, Any]] = None) -> Path:
        registry = dict(registry or self._read_registry())
        root = Path(str(registry["authority_root"])).resolve()
        if not root.exists():
            raise HarnessError("authoritative worktree is missing: %s" % root, code=EXIT_WORKSPACE)
        linked = discover_git_context(root)
        if linked.common_dir != self.context.common_dir:
            raise HarnessError("authority root belongs to another repository", code=EXIT_VERIFY)
        return root

    def task_dir(self, registry: Optional[Mapping[str, Any]] = None) -> Path:
        registry = dict(registry or self._read_registry())
        root = self.authority_root(registry)
        rel = registry.get("task_relpath")
        if rel != "%s/%s" % (TASK_REL_ROOT, self.task_id):
            raise HarnessError("task registry path mismatch", code=EXIT_VERIFY)
        return safe_child(root, rel, "task artifact path")

    def state_path(self, registry: Optional[Mapping[str, Any]] = None) -> Path:
        return self.task_dir(registry) / "state.json"

    def evidence_path(self, registry: Optional[Mapping[str, Any]] = None) -> Path:
        return self.task_dir(registry) / "evidence.jsonl"

    def _read_state(self, registry: Optional[Mapping[str, Any]] = None) -> Dict[str, Any]:
        state = _need_dict(read_json(self.state_path(registry)), "task state")
        if state.get("schema_version") != SCHEMA_VERSION or state.get("contract") != CONTRACT:
            raise HarnessError("task state schema mismatch", code=EXIT_VERIFY)
        if state.get("task_id") != self.task_id:
            raise HarnessError("task state identity mismatch", code=EXIT_VERIFY)
        _need_int(state.get("version"), "state.version", 1)
        if state.get("phase") not in PHASES:
            raise HarnessError("task state has invalid phase", code=EXIT_VERIFY)
        owner = state.get("loop_owner")
        if owner is not None:
            validate_owner(owner)
        _need_int(state.get("verify_retry_count", 0), "state.verify_retry_count")
        _need_int(state.get("max_verify_retries", 2), "state.max_verify_retries")
        return state

    def _recover_transaction(self) -> None:
        if not self.txn_path.exists():
            return
        txn = _need_dict(read_json(self.txn_path, max_bytes=16 * 1024 * 1024), "transaction")
        if txn.get("schema_version") != SCHEMA_VERSION or txn.get("task_id") != self.task_id:
            raise HarnessError("invalid pending task transaction", code=EXIT_VERIFY)
        registry = self._read_registry()
        state = self._read_state(registry)
        current_state_digest = digest_json(state)
        current_registry_digest = digest_json(registry)
        old_state = txn.get("old_state_digest")
        old_registry = txn.get("old_registry_digest")
        new_state = _need_dict(txn.get("new_state"), "transaction.new_state")
        new_registry = _need_dict(txn.get("new_registry"), "transaction.new_registry")
        if current_state_digest not in (old_state, digest_json(new_state)):
            raise HarnessError("pending transaction conflicts with task state", code=EXIT_VERIFY)
        if current_registry_digest not in (old_registry, digest_json(new_registry)):
            raise HarnessError("pending transaction conflicts with task registry", code=EXIT_VERIFY)
        write_json_atomic(self.state_path(registry), new_state, mode=0o644)
        write_json_atomic(self.registry_path, new_registry)
        event = txn.get("event")
        if event is not None:
            events, previous = _read_evidence(self.evidence_path(new_registry), self.task_id)
            if len(events) + 1 == event.get("seq") and previous == event.get("prev_hash"):
                _append_event(self.evidence_path(new_registry), event, self.task_id)
            elif events and events[-1].get("hash") == event.get("hash"):
                pass
            else:
                raise HarnessError("pending transaction conflicts with evidence log", code=EXIT_VERIFY)
        self.txn_path.unlink()
        fsync_dir(self.txn_path.parent)

    def read(self) -> Tuple[Dict[str, Any], Dict[str, Any]]:
        with FileMutex(self.lock_path):
            self._recover_transaction()
            registry = self._read_registry()
            state = self._read_state(registry)
            if registry.get("state_version", state["version"]) != state["version"]:
                raise HarnessError("registry/state version mismatch", code=EXIT_VERIFY)
            return state, registry

    def _mutate_locked(
        self,
        expected_version: int,
        actor: str,
        kind: str,
        payload: Mapping[str, Any],
        callback: Callable[[Dict[str, Any], Dict[str, Any]], None],
    ) -> Tuple[Dict[str, Any], Dict[str, Any], Dict[str, Any]]:
        self._recover_transaction()
        registry = self._read_registry()
        state = self._read_state(registry)
        if registry.get("state_version", state["version"]) != state["version"]:
            raise HarnessError("registry/state version mismatch", code=EXIT_VERIFY)
        if state["version"] != expected_version:
            raise HarnessError(
                "state version conflict: expected %d, current %d" % (expected_version, state["version"]),
                code=EXIT_CONFLICT,
                details={"expected_version": expected_version, "current_version": state["version"]},
            )
        old_state_digest = digest_json(state)
        old_registry_digest = digest_json(registry)
        callback(state, registry)
        state["version"] = expected_version + 1
        state["updated_at"] = utc_now()
        registry["version"] = int(registry.get("version", 1)) + 1
        registry["state_version"] = state["version"]
        registry["updated_at"] = utc_now()
        event = _make_event(self.evidence_path(registry), self.task_id, kind, actor, payload)
        txn = {
            "schema_version": SCHEMA_VERSION,
            "contract": CONTRACT,
            "task_id": self.task_id,
            "old_state_digest": old_state_digest,
            "old_registry_digest": old_registry_digest,
            "new_state": state,
            "new_registry": registry,
            "event": event,
        }
        write_json_atomic(self.txn_path, txn)
        write_json_atomic(self.state_path(registry), state, mode=0o644)
        write_json_atomic(self.registry_path, registry)
        _append_event(self.evidence_path(registry), event, self.task_id)
        self.txn_path.unlink()
        fsync_dir(self.txn_path.parent)
        return state, registry, event

    def mutate(
        self,
        expected_version: int,
        actor: str,
        kind: str,
        payload: Mapping[str, Any],
        callback: Callable[[Dict[str, Any], Dict[str, Any]], None],
    ) -> Tuple[Dict[str, Any], Dict[str, Any], Dict[str, Any]]:
        with FileMutex(self.lock_path):
            return self._mutate_locked(expected_version, actor, kind, payload, callback)

    def append_evidence(
        self,
        expected_version: int,
        actor: str,
        kind: str,
        payload: Mapping[str, Any],
        token: str,
    ) -> Dict[str, Any]:
        def no_state_change(state: Dict[str, Any], registry: Dict[str, Any]) -> None:
            self.require_lease(state, registry, token)

        state, registry, event = self.mutate(expected_version, actor, kind, payload, no_state_change)
        return event

    @staticmethod
    def require_lease(state: Mapping[str, Any], registry: Mapping[str, Any], token: str) -> Dict[str, Any]:
        lease = registry.get("lease")
        if not isinstance(lease, dict):
            raise HarnessError("task has no active loop-owner lease", code=EXIT_LEASE)
        expires = lease.get("expires_epoch")
        if not isinstance(expires, (int, float)) or expires <= time.time():
            raise HarnessError("loop-owner lease has expired", code=EXIT_LEASE)
        supplied = token_hash(token)
        expected = lease.get("token_hash")
        if not isinstance(expected, str) or not secrets.compare_digest(supplied, expected):
            raise HarnessError("invalid loop-owner lease token", code=EXIT_LEASE)
        if state.get("loop_owner") != lease.get("owner"):
            raise HarnessError("state/lease owner mismatch", code=EXIT_VERIFY)
        return lease



def _validate_title(title: str, task_id: str) -> str:
    if not isinstance(title, str):
        raise HarnessError("task title must be a string", code=EXIT_DATA)
    normalized = title.strip() or task_id
    if len(normalized) > 160 or any(ord(ch) < 32 for ch in normalized):
        raise HarnessError("task title must be one line and at most 160 characters", code=EXIT_DATA)
    return normalized


def _markdown_section_issues(path: Path, sections: Sequence[str], label: str) -> List[str]:
    issues: List[str] = []
    try:
        info = path.lstat()
    except FileNotFoundError:
        return ["missing %s: %s" % (label, path.name)]
    if stat.S_ISLNK(info.st_mode) or not stat.S_ISREG(info.st_mode):
        return ["%s must be a regular non-symlink file" % label]
    if info.st_size > MAX_ARTIFACT_BYTES:
        return ["%s exceeds %d bytes" % (label, MAX_ARTIFACT_BYTES)]
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        return ["%s is not readable UTF-8: %s" % (label, exc)]
    lines = text.splitlines()
    positions: Dict[str, int] = {}
    for index, line in enumerate(lines):
        stripped = line.strip()
        for section in sections:
            if stripped == "## %s" % section and section not in positions:
                positions[section] = index
    for section in sections:
        if section not in positions:
            issues.append("%s is missing section: %s" % (label, section))
            continue
        start = positions[section] + 1
        later = [position for position in positions.values() if position > positions[section]]
        end = min(later) if later else len(lines)
        content = "\n".join(lines[start:end]).strip()
        if not content:
            issues.append("%s section is incomplete: %s" % (label, section))
    return issues


def _artifact_issues(store: "TaskStore", registry: Mapping[str, Any]) -> Dict[str, List[str]]:
    root = store.task_dir(registry)
    return {
        "brief": _markdown_section_issues(root / "brief.md", BRIEF_SECTIONS, "brief.md"),
        "plan": _markdown_section_issues(root / "plan.md", PLAN_SECTIONS, "plan.md"),
    }


def _latest_verification_passed(events: Sequence[Mapping[str, Any]]) -> bool:
    """Require the latest verification after the most recent verifying transition to pass."""
    verifying_seq = 0
    for event in events:
        payload = event.get("payload")
        if event.get("kind") == "state-transition" and isinstance(payload, dict) and payload.get("target") == "verifying":
            verifying_seq = int(event.get("seq", 0))
    if not verifying_seq:
        return False
    latest: Optional[Mapping[str, Any]] = None
    for event in events:
        if int(event.get("seq", 0)) <= verifying_seq or event.get("kind") not in VERIFICATION_EVIDENCE_KINDS:
            continue
        payload = event.get("payload")
        if isinstance(payload, dict):
            latest = payload
    if latest is None:
        return False
    return bool(
        latest.get("passed") is True
        or latest.get("exit_code") == 0
        or latest.get("status") in ("passed", "success")
    )

def init_task(
    context: GitContext,
    task_id: str,
    max_verify_retries: int,
    title: str,
    force_existing: bool = False,
) -> Tuple[TaskStore, Dict[str, Any]]:
    task_id = validate_identifier(task_id, "task id")
    title = _validate_title(title, task_id)
    store = TaskStore(context, task_id)
    global_lock = store.runtime / "locks" / "__registry__.lock"
    with FileMutex(global_lock):
        if store.registry_path.exists():
            if force_existing:
                state, _ = store.read()
                return store, state
            raise HarnessError("task already exists: %s" % task_id, code=EXIT_CONFLICT)
        task_rel = "%s/%s" % (TASK_REL_ROOT, task_id)
        task_dir = safe_child(context.worktree_root, task_rel, "task directory")
        if task_dir.exists() and any(task_dir.iterdir()):
            raise HarnessError("task artifact directory already exists and is non-empty", code=EXIT_CONFLICT)
        task_dir.mkdir(parents=True, exist_ok=True)
        created = utc_now()
        state = {
            "schema_version": SCHEMA_VERSION,
            "contract": CONTRACT,
            "task_id": task_id,
            "version": 1,
            "phase": "clarifying",
            "loop_owner": None,
            "verify_retry_count": 0,
            "max_verify_retries": max_verify_retries,
            "blocked_from": None,
            "created_at": created,
            "updated_at": created,
        }
        registry = {
            "schema_version": SCHEMA_VERSION,
            "contract": CONTRACT,
            "task_id": task_id,
            "version": 1,
            "state_version": 1,
            # Local runtime metadata can be absolute; committed task artifacts remain portable.
            "authority_root": str(context.worktree_root),
            "task_relpath": task_rel,
            "lease": None,
            "workspaces": {},
            "created_at": created,
            "updated_at": created,
        }
        brief = task_dir / "brief.md"
        plan = task_dir / "plan.md"
        brief.write_text(
            "# %s\n\n## Goal\n\n## Non-goals\n\n## Acceptance criteria\n\n## Authority and external effects\n"
            % title,
            encoding="utf-8",
        )
        plan.write_text("# Plan\n\n## Slices\n\n## Risks and dependencies\n\n## Ownership\n", encoding="utf-8")
        write_json_atomic(task_dir / "state.json", state, mode=0o644)
        event = _make_event(task_dir / "evidence.jsonl", task_id, "task-init", getpass.getuser(), {"title": title})
        _append_event(task_dir / "evidence.jsonl", event, task_id)
        write_json_atomic(store.registry_path, registry)
        return store, state


def effective_lease(registry: Mapping[str, Any]) -> Optional[Dict[str, Any]]:
    lease = registry.get("lease")
    if not isinstance(lease, dict):
        return None
    result = {key: value for key, value in lease.items() if key != "token_hash"}
    result["active"] = isinstance(lease.get("expires_epoch"), (int, float)) and lease["expires_epoch"] > time.time()
    return result


def acquire_owner(
    store: TaskStore,
    expected_version: int,
    owner: str,
    ttl: int,
    actor: str,
    recover: bool = False,
) -> Tuple[Dict[str, Any], str]:
    owner = validate_owner(owner)
    if ttl < 10 or ttl > 86400:
        raise HarnessError("lease TTL must be 10..86400 seconds", code=EXIT_DATA)
    token = secrets.token_urlsafe(32)
    now = time.time()

    def callback(state: Dict[str, Any], registry: Dict[str, Any]) -> None:
        current = registry.get("lease")
        if isinstance(current, dict) and current.get("expires_epoch", 0) > now:
            raise HarnessError("another loop owner holds an active lease", code=EXIT_LEASE)
        if isinstance(current, dict) and not recover:
            raise HarnessError("expired lease exists; use owner recover for an explicit takeover", code=EXIT_LEASE)
        state["loop_owner"] = owner
        registry["lease"] = {
            "owner": owner,
            "token_hash": token_hash(token),
            "issued_at": utc_now(),
            "issued_epoch": now,
            "expires_epoch": now + ttl,
            "generation": int(current.get("generation", 0)) + 1 if isinstance(current, dict) else 1,
        }

    kind = "owner-recover" if recover else "owner-acquire"
    state, registry, _ = store.mutate(expected_version, actor, kind, {"owner": owner, "ttl_seconds": ttl}, callback)
    return state, token


def release_owner(store: TaskStore, expected_version: int, token: str, actor: str) -> Dict[str, Any]:
    def callback(state: Dict[str, Any], registry: Dict[str, Any]) -> None:
        lease = store.require_lease(state, registry, token)
        state["loop_owner"] = None
        registry["lease"] = None

    state, _, _ = store.mutate(expected_version, actor, "owner-release", {}, callback)
    return state


def handoff_owner(
    store: TaskStore,
    expected_version: int,
    token: str,
    new_owner: str,
    ttl: int,
    actor: str,
) -> Tuple[Dict[str, Any], str]:
    new_owner = validate_owner(new_owner)
    if ttl < 10 or ttl > 86400:
        raise HarnessError("lease TTL must be 10..86400 seconds", code=EXIT_DATA)
    new_token = secrets.token_urlsafe(32)
    now = time.time()

    def callback(state: Dict[str, Any], registry: Dict[str, Any]) -> None:
        old = store.require_lease(state, registry, token)
        old_owner = old["owner"]
        state["loop_owner"] = new_owner
        registry["lease"] = {
            "owner": new_owner,
            "token_hash": token_hash(new_token),
            "issued_at": utc_now(),
            "issued_epoch": now,
            "expires_epoch": now + ttl,
            "generation": int(old.get("generation", 0)) + 1,
        }

    state, _, _ = store.mutate(
        expected_version, actor, "owner-handoff", {"new_owner": new_owner, "ttl_seconds": ttl}, callback
    )
    return state, new_token


def check_owner(store: TaskStore, token: str) -> Tuple[Dict[str, Any], Dict[str, Any]]:
    """Read-only lease validation for orchestration loops before each owned action."""
    state, registry = store.read()
    store.require_lease(state, registry, token)
    lease = effective_lease(registry)
    if lease is None:
        raise HarnessError("active lease is missing", code=EXIT_LEASE)
    return state, lease


def heartbeat_owner(
    store: TaskStore,
    expected_version: int,
    token: str,
    ttl: int,
    actor: str,
) -> Dict[str, Any]:
    if ttl < 10 or ttl > 86400:
        raise HarnessError("lease TTL must be 10..86400 seconds", code=EXIT_DATA)
    now = time.time()

    def callback(state: Dict[str, Any], registry: Dict[str, Any]) -> None:
        lease = store.require_lease(state, registry, token)
        lease["expires_epoch"] = now + ttl
        lease["refreshed_at"] = utc_now()

    state, _, _ = store.mutate(
        expected_version, actor, "owner-heartbeat", {"ttl_seconds": ttl}, callback
    )
    return state


def transition_task(
    store: TaskStore,
    expected_version: int,
    token: str,
    target: str,
    actor: str,
    reason: str,
) -> Dict[str, Any]:
    if target not in PHASES:
        raise HarnessError("unknown target phase: %s" % target, code=EXIT_STATE)

    def callback(state: Dict[str, Any], registry: Dict[str, Any]) -> None:
        store.require_lease(state, registry, token)
        current = state["phase"]
        if target not in TRANSITIONS[current]:
            raise HarnessError("invalid state transition: %s -> %s" % (current, target), code=EXIT_STATE)
        artifacts = _artifact_issues(store, registry)
        required_issues: List[str] = []
        if target in ("planned", "executing", "verifying", "done"):
            required_issues.extend(artifacts["brief"])
        if target in ("executing", "verifying", "done"):
            required_issues.extend(artifacts["plan"])
        if required_issues:
            raise HarnessError(
                "task artifacts are incomplete: %s" % "; ".join(required_issues),
                code=EXIT_STATE,
                details={"issues": required_issues},
            )
        if target == "done":
            events, _ = _read_evidence(store.evidence_path(registry), store.task_id)
            if not _latest_verification_passed(events):
                raise HarnessError(
                    "done requires successful deterministic verification evidence",
                    code=EXIT_STATE,
                )
        if current == "verifying" and target == "executing":
            retries = int(state.get("verify_retry_count", 0))
            maximum = int(state.get("max_verify_retries", 0))
            if retries >= maximum:
                raise HarnessError("verification retry limit reached", code=EXIT_STATE)
            state["verify_retry_count"] = retries + 1
        if target == "blocked":
            state["blocked_from"] = current
        elif current == "blocked":
            state["blocked_from"] = None
        state["phase"] = target

    state, _, _ = store.mutate(
        expected_version,
        actor,
        "state-transition",
        {"target": target, "reason": reason[:4096]},
        callback,
    )
    return state


def _worktree_porcelain(context: GitContext) -> List[Dict[str, Any]]:
    text = run_git(["worktree", "list", "--porcelain"], context.worktree_root).stdout
    records: List[Dict[str, Any]] = []
    current: Dict[str, Any] = {}
    for line in text.splitlines() + [""]:
        if not line:
            if current:
                records.append(current)
                current = {}
            continue
        key, _, value = line.partition(" ")
        current[key] = value if value else True
    return records


def _canonical_workspace_path(path: Path) -> Path:
    parent = path.expanduser().absolute().parent
    parent.mkdir(parents=True, exist_ok=True)
    parent_real = parent.resolve(strict=True)
    return parent_real / path.name


def _paths_nested(left: Path, right: Path) -> bool:
    left_s = os.path.normcase(str(left.resolve(strict=False)))
    right_s = os.path.normcase(str(right.resolve(strict=False)))
    try:
        common = os.path.normcase(os.path.commonpath([left_s, right_s]))
    except ValueError:
        return False
    return common == left_s or common == right_s


def _assert_workspace_location(context: GitContext, path: Path) -> None:
    if _paths_nested(path, context.common_dir):
        raise HarnessError("workspace path may not contain or be inside the Git common directory", code=EXIT_WORKSPACE)
    for item in _worktree_porcelain(context):
        existing_raw = item.get("worktree")
        if not existing_raw:
            continue
        existing = Path(str(existing_raw))
        if _paths_nested(path, existing):
            raise HarnessError(
                "workspace path may not contain or be inside an existing Git worktree: %s" % existing,
                code=EXIT_WORKSPACE,
            )


def _assert_unique_workspace_path(registry: Mapping[str, Any], path: Path, workspace_id: Optional[str] = None) -> None:
    for item_id, item in _need_dict(registry.get("workspaces", {}), "workspaces").items():
        if workspace_id is not None and item_id == workspace_id:
            continue
        existing = Path(str(item["path"]))
        if _paths_nested(path, existing):
            raise HarnessError("workspace path overlaps registered workspace %s" % item_id, code=EXIT_WORKSPACE)


def _git_status_clean(path: Path) -> bool:
    result = run_git(["status", "--porcelain=v1", "--untracked-files=all"], path)
    return not result.stdout.strip()


def _head_commit(path: Path) -> str:
    return run_git(["rev-parse", "HEAD^{commit}"], path).stdout.strip()


def _is_detached(path: Path) -> bool:
    result = run_git(["symbolic-ref", "-q", "HEAD"], path, check=False)
    return result.returncode != 0


def _set_reviewer_read_only(path: Path, read_only: bool) -> None:
    if os.name == "nt":
        # Runtime verification remains authoritative where POSIX mode bits are not enforced.
        return
    dirs: List[Path] = []
    files: List[Path] = []
    for current, names, filenames in os.walk(str(path), topdown=True, followlinks=False):
        current_path = Path(current)
        dirs.append(current_path)
        files.extend(current_path / name for name in filenames)
    if read_only:
        for item in files:
            try:
                item.chmod(item.stat().st_mode & ~0o222)
            except OSError:
                pass
        for item in reversed(dirs):
            try:
                item.chmod(item.stat().st_mode & ~0o222)
            except OSError:
                pass
    else:
        for item in dirs:
            try:
                item.chmod(item.stat().st_mode | 0o700)
            except OSError:
                pass
        for item in files:
            try:
                item.chmod(item.stat().st_mode | 0o600)
            except OSError:
                pass


def create_workspace(
    store: TaskStore,
    expected_version: int,
    token: str,
    workspace_id: str,
    role: str,
    path: Path,
    actor: str,
    commit: Optional[str],
    branch: Optional[str],
    start_point: str,
) -> Dict[str, Any]:
    workspace_id = validate_identifier(workspace_id, "workspace id")
    if role not in WORKSPACE_ROLES:
        raise HarnessError("invalid workspace role", code=EXIT_WORKSPACE)
    target = _canonical_workspace_path(path)
    _assert_workspace_location(store.context, target)
    if target.exists() and any(target.iterdir() if target.is_dir() else [target]):
        raise HarnessError("workspace target must not exist or must be empty", code=EXIT_WORKSPACE)
    state, registry = store.read()
    if state["version"] != expected_version:
        raise HarnessError("state version conflict before workspace creation", code=EXIT_CONFLICT)
    store.require_lease(state, registry, token)
    workspaces = _need_dict(registry.get("workspaces", {}), "workspaces")
    if workspace_id in workspaces:
        raise HarnessError("workspace id already exists", code=EXIT_CONFLICT)
    _assert_unique_workspace_path(registry, target)
    if role == "integrator" and any(item.get("role") == "integrator" for item in workspaces.values()):
        raise HarnessError("task already has an integrator", code=EXIT_WORKSPACE)
    if role == "reviewer":
        if not commit or not FULL_COMMIT_RE.fullmatch(commit):
            raise HarnessError("reviewer snapshot must be an exact full commit SHA, not a ref", code=EXIT_WORKSPACE)
        base_commit = run_git(
            ["rev-parse", "--verify", "%s^{commit}" % commit], store.context.worktree_root
        ).stdout.strip()
        if base_commit.lower() != commit.lower():
            raise HarnessError("reviewer commit did not resolve identically", code=EXIT_WORKSPACE)
        run_git(["worktree", "add", "--detach", str(target), base_commit], store.context.worktree_root, timeout=120)
    else:
        if not branch:
            raise HarnessError("writable workspaces require a new branch name", code=EXIT_WORKSPACE)
        if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._/-]{0,127}", branch) or ".." in branch or branch.endswith("/"):
            raise HarnessError("invalid workspace branch name", code=EXIT_WORKSPACE)
        run_git(["check-ref-format", "--branch", branch], store.context.worktree_root)
        base_commit = run_git(
            ["rev-parse", "--verify", "%s^{commit}" % start_point], store.context.worktree_root
        ).stdout.strip()
        run_git(["worktree", "add", "-b", branch, str(target), base_commit], store.context.worktree_root, timeout=120)
    try:
        linked = discover_git_context(target)
        if linked.common_dir != store.context.common_dir:
            raise HarnessError("created workspace is not linked to this repository", code=EXIT_WORKSPACE)
        head = _head_commit(target)
        if not _git_status_clean(target):
            raise HarnessError("new workspace is not clean", code=EXIT_WORKSPACE)
        if role == "reviewer" and (head.lower() != base_commit.lower() or not _is_detached(target)):
            raise HarnessError("reviewer workspace is not detached at the requested commit", code=EXIT_WORKSPACE)
        if role == "reviewer":
            _set_reviewer_read_only(target, True)

        def callback(task_state: Dict[str, Any], task_registry: Dict[str, Any]) -> None:
            store.require_lease(task_state, task_registry, token)
            items = _need_dict(task_registry.setdefault("workspaces", {}), "workspaces")
            if workspace_id in items:
                raise HarnessError("workspace id was concurrently registered", code=EXIT_CONFLICT)
            _assert_unique_workspace_path(task_registry, target)
            if role == "integrator" and any(item.get("role") == "integrator" for item in items.values()):
                raise HarnessError("task already has an integrator", code=EXIT_WORKSPACE)
            items[workspace_id] = {
                "id": workspace_id,
                "role": role,
                "path": str(target),
                "head": head,
                "base_commit": base_commit,
                "snapshot_commit": head if role == "reviewer" else None,
                "read_only": role == "reviewer",
                "path_rules": [],
                "branch": branch if role != "reviewer" else None,
                "created_at": utc_now(),
            }

        new_state, new_registry, _ = store.mutate(
            expected_version,
            actor,
            "workspace-create",
            {"workspace_id": workspace_id, "role": role, "head": head, "base_commit": base_commit},
            callback,
        )
        return new_registry["workspaces"][workspace_id]
    except Exception:
        if role == "reviewer" and target.exists():
            _set_reviewer_read_only(target, False)
        run_git(["worktree", "remove", "--force", str(target)], store.context.worktree_root, check=False, timeout=120)
        raise


def claim_paths(
    store: TaskStore,
    expected_version: int,
    token: str,
    workspace_id: str,
    rules: Sequence[str],
    actor: str,
) -> Dict[str, Any]:
    normalized = [ensure_relative_path(rule, "path rule", allow_glob=True) for rule in rules]
    if not normalized:
        raise HarnessError("at least one path rule is required", code=EXIT_USAGE)

    def callback(state: Dict[str, Any], registry: Dict[str, Any]) -> None:
        store.require_lease(state, registry, token)
        workspaces = _need_dict(registry.get("workspaces", {}), "workspaces")
        if workspace_id not in workspaces:
            raise HarnessError("unknown workspace: %s" % workspace_id, code=EXIT_WORKSPACE)
        target = workspaces[workspace_id]
        if target.get("role") not in WRITABLE_ROLES:
            raise HarnessError("reviewer workspace cannot claim writable paths", code=EXIT_WORKSPACE)
        combined = list(target.get("path_rules", [])) + normalized
        if len(set(combined)) != len(combined):
            raise HarnessError("duplicate path rule", code=EXIT_CONFLICT)
        for other_id, other in workspaces.items():
            if other_id == workspace_id or other.get("role") not in WRITABLE_ROLES:
                continue
            for new_rule in normalized:
                for existing in other.get("path_rules", []):
                    if patterns_overlap(new_rule, existing):
                        raise HarnessError(
                            "path ownership overlaps %s: %s vs %s" % (other_id, new_rule, existing),
                            code=EXIT_CONFLICT,
                        )
        target["path_rules"] = combined

    state, registry, _ = store.mutate(
        expected_version,
        actor,
        "workspace-claim",
        {"workspace_id": workspace_id, "rules": normalized},
        callback,
    )
    return registry["workspaces"][workspace_id]


def _git_paths(path: Path, args: Sequence[str]) -> List[str]:
    output = run_git(list(args), path).stdout
    values = []
    for raw in output.split("\x00"):
        if not raw:
            continue
        if "\ufffd" in raw:
            raise HarnessError("Git path output is not valid UTF-8", code=EXIT_WORKSPACE)
        values.append(ensure_relative_path(raw, "changed path"))
    return values


def _git_name_status_paths(path: Path, args: Sequence[str]) -> List[str]:
    output = run_git(list(args), path).stdout
    fields = output.split("\x00")
    if fields and not fields[-1]:
        fields.pop()
    values: List[str] = []
    index = 0
    while index < len(fields):
        status = fields[index]
        index += 1
        if not re.fullmatch(r"[A-Z][0-9]*", status):
            raise HarnessError("Git name-status output is malformed", code=EXIT_WORKSPACE)
        path_count = 2 if status.startswith(("R", "C")) else 1
        if index + path_count > len(fields):
            raise HarnessError("Git name-status output is truncated", code=EXIT_WORKSPACE)
        for raw in fields[index : index + path_count]:
            if "\ufffd" in raw:
                raise HarnessError("Git path output is not valid UTF-8", code=EXIT_WORKSPACE)
            values.append(ensure_relative_path(raw, "changed path"))
        index += path_count
    return values


def workspace_changed_paths(path: Path, base_commit: str) -> List[str]:
    """Return committed, staged, unstaged, unmerged, and untracked paths."""
    groups = [
        _git_name_status_paths(path, ["diff", "--name-status", "-z", "%s..HEAD" % base_commit, "--"]),
        _git_name_status_paths(path, ["diff", "--cached", "--name-status", "-z", "--"]),
        _git_name_status_paths(path, ["diff", "--name-status", "-z", "--"]),
        _git_name_status_paths(path, ["diff", "--name-status", "--diff-filter=U", "-z", "--"]),
        _git_paths(path, ["ls-files", "--others", "--exclude-standard", "-z"]),
    ]
    return sorted({item for group in groups for item in group})


def _changed_symlink_issues(root: Path, paths: Sequence[str]) -> List[str]:
    issues: List[str] = []
    root = root.resolve(strict=True)
    for relative in paths:
        current = root
        for part in PurePosixPath(relative).parts:
            current = current / part
            try:
                info = current.lstat()
            except FileNotFoundError:
                break
            if not stat.S_ISLNK(info.st_mode):
                continue
            resolved = current.resolve(strict=False)
            try:
                resolved.relative_to(root)
            except ValueError:
                issues.append("changed symlink escapes workspace: %s" % relative)
            break
    return issues


def verify_workspace_record(store: TaskStore, record: Mapping[str, Any]) -> List[str]:
    issues: List[str] = []
    path = Path(str(record.get("path", "")))
    if not path.is_absolute() or not path.exists():
        return ["workspace missing: %s" % record.get("id")]
    try:
        linked = discover_git_context(path)
        if linked.common_dir != store.context.common_dir:
            issues.append("workspace belongs to another repository: %s" % record.get("id"))
        head = _head_commit(path)
        if record.get("role") == "reviewer":
            if head != record.get("snapshot_commit"):
                issues.append("reviewer HEAD moved: %s" % record.get("id"))
            if not _is_detached(path):
                issues.append("reviewer is not detached: %s" % record.get("id"))
            if not _git_status_clean(path):
                issues.append("reviewer snapshot is dirty: %s" % record.get("id"))
        else:
            if os.path.normcase(str(path.resolve())) == os.path.normcase(str(store.authority_root().resolve())):
                issues.append("writable workspace shares the authority working tree: %s" % record.get("id"))
            if _is_detached(path):
                issues.append("writable workspace is detached: %s" % record.get("id"))
            else:
                branch = run_git(["symbolic-ref", "--short", "HEAD"], path).stdout.strip()
                if branch != record.get("branch"):
                    issues.append("writable workspace branch moved: %s" % record.get("id"))
            base_commit = record.get("base_commit")
            if not isinstance(base_commit, str) or not FULL_COMMIT_RE.fullmatch(base_commit):
                issues.append("workspace base commit is invalid: %s" % record.get("id"))
            else:
                ancestor = run_git(["merge-base", "--is-ancestor", base_commit, "HEAD"], path, check=False)
                if ancestor.returncode != 0:
                    issues.append("workspace HEAD no longer descends from its base: %s" % record.get("id"))
                changed = workspace_changed_paths(path, base_commit)
                rules = record.get("path_rules", [])
                if changed and not rules:
                    issues.append("writable workspace has unclaimed changed paths: %s" % record.get("id"))
                for relative in changed:
                    if rules and not match_any(relative, rules):
                        issues.append("changed path is outside ownership for %s: %s" % (record.get("id"), relative))
                issues.extend(_changed_symlink_issues(path, changed))
    except HarnessError as exc:
        issues.append("workspace %s: %s" % (record.get("id"), exc))
    return issues


def remove_workspace(
    store: TaskStore,
    expected_version: int,
    token: str,
    workspace_id: str,
    actor: str,
    merged_into: str,
    force: bool,
    reason: str,
) -> None:
    # Hold the task mutex across safety checks, the Git side effect, and registry commit.
    # This prevents another workctl mutation from winning the same CAS during cleanup.
    with FileMutex(store.lock_path, timeout=30.0, stale_after=300.0):
        store._recover_transaction()
        registry = store._read_registry()
        state = store._read_state(registry)
        if registry.get("state_version", state["version"]) != state["version"]:
            raise HarnessError("registry/state version mismatch", code=EXIT_VERIFY)
        if state["version"] != expected_version:
            raise HarnessError("state version conflict before workspace removal", code=EXIT_CONFLICT)
        store.require_lease(state, registry, token)
        workspaces = _need_dict(registry.get("workspaces", {}), "workspaces")
        if workspace_id not in workspaces:
            raise HarnessError("unknown workspace", code=EXIT_WORKSPACE)
        record = dict(workspaces[workspace_id])
        path = Path(record["path"])
        issues = verify_workspace_record(store, record)
        if issues and not force:
            raise HarnessError("unsafe workspace removal: %s" % "; ".join(issues), code=EXIT_WORKSPACE)
        if path.exists() and record.get("role") in WRITABLE_ROLES:
            clean = _git_status_clean(path)
            if not clean and not force:
                raise HarnessError("refusing to remove a dirty writable workspace", code=EXIT_WORKSPACE)
            if clean and not force:
                target = run_git(["rev-parse", "%s^{commit}" % merged_into], store.context.worktree_root).stdout.strip()
                head = _head_commit(path)
                merged = run_git(["merge-base", "--is-ancestor", head, target], store.context.worktree_root, check=False)
                if merged.returncode != 0:
                    raise HarnessError("workspace HEAD is not merged into %s" % merged_into, code=EXIT_WORKSPACE)
        if force and not reason.strip():
            raise HarnessError("forced workspace removal requires --reason", code=EXIT_USAGE)
        if record.get("role") == "reviewer" and path.exists():
            _set_reviewer_read_only(path, False)
        if path.exists():
            git_args = ["worktree", "remove"]
            if force:
                git_args.append("--force")
            git_args.append(str(path))
            run_git(git_args, store.context.worktree_root, timeout=120)

        def callback(task_state: Dict[str, Any], task_registry: Dict[str, Any]) -> None:
            store.require_lease(task_state, task_registry, token)
            current = _need_dict(task_registry.get("workspaces", {}), "workspaces")
            current_record = current.get(workspace_id)
            if current_record is None or current_record.get("path") != record.get("path"):
                raise HarnessError("workspace registration changed concurrently", code=EXIT_CONFLICT)
            del current[workspace_id]

        store._mutate_locked(
            expected_version,
            actor,
            "workspace-remove",
            {"workspace_id": workspace_id, "forced": force, "reason": reason[:4096]},
            callback,
        )


def prune_stale_workspace(
    store: TaskStore,
    expected_version: int,
    token: str,
    workspace_id: str,
    actor: str,
    reason: str,
) -> None:
    if not reason.strip():
        raise HarnessError("stale workspace pruning requires --reason", code=EXIT_USAGE)
    with FileMutex(store.lock_path, timeout=30.0, stale_after=300.0):
        store._recover_transaction()
        registry = store._read_registry()
        state = store._read_state(registry)
        if state["version"] != expected_version:
            raise HarnessError("state version conflict before stale pruning", code=EXIT_CONFLICT)
        store.require_lease(state, registry, token)
        workspaces = _need_dict(registry.get("workspaces", {}), "workspaces")
        record = workspaces.get(workspace_id)
        if not isinstance(record, dict):
            raise HarnessError("unknown workspace", code=EXIT_WORKSPACE)
        path = Path(str(record.get("path", "")))
        if path.exists():
            raise HarnessError("workspace path still exists; use workspace remove", code=EXIT_WORKSPACE)
        # Remove only Git metadata already proven stale; never delete a filesystem path here.
        run_git(["worktree", "prune", "--expire", "now"], store.context.worktree_root)
        listed = {
            os.path.normcase(str(Path(str(item.get("worktree", ""))).resolve(strict=False)))
            for item in _worktree_porcelain(store.context)
            if item.get("worktree")
        }
        if os.path.normcase(str(path.resolve(strict=False))) in listed:
            raise HarnessError("Git still considers the missing workspace active", code=EXIT_WORKSPACE)

        def callback(task_state: Dict[str, Any], task_registry: Dict[str, Any]) -> None:
            store.require_lease(task_state, task_registry, token)
            current = _need_dict(task_registry.get("workspaces", {}), "workspaces")
            current_record = current.get(workspace_id)
            if not isinstance(current_record, dict) or current_record.get("path") != record.get("path"):
                raise HarnessError("workspace registration changed concurrently", code=EXIT_CONFLICT)
            del current[workspace_id]

        store._mutate_locked(
            expected_version,
            actor,
            "workspace-prune-stale",
            {"workspace_id": workspace_id, "reason": reason[:4096]},
            callback,
        )


def assert_writable_context(store: TaskStore, cwd: Path) -> None:
    _, registry = store.read()
    cwd_root = discover_git_context(cwd).worktree_root
    normalized = os.path.normcase(str(cwd_root.resolve()))
    for record in _need_dict(registry.get("workspaces", {}), "workspaces").values():
        if os.path.normcase(str(Path(record["path"]).resolve(strict=False))) == normalized:
            if record.get("role") == "reviewer" or record.get("read_only"):
                raise HarnessError("reviewer workspace is read-only by task policy", code=EXIT_WORKSPACE)
            issues = verify_workspace_record(store, record)
            if issues:
                raise HarnessError("workspace write guard failed: %s" % "; ".join(issues), code=EXIT_WORKSPACE)
            return
    raise HarnessError("current worktree is not a registered writable workspace", code=EXIT_WORKSPACE)


def verify_task(store: TaskStore) -> Dict[str, Any]:
    issues: List[str] = []
    with FileMutex(store.lock_path):
        try:
            store._recover_transaction()
            registry = store._read_registry()
            state = store._read_state(registry)
            events, last_hash = _read_evidence(store.evidence_path(registry), store.task_id)
        except HarnessError as exc:
            return {"ok": False, "issues": [str(exc)]}
        if registry.get("state_version", state["version"]) != state["version"]:
            issues.append("registry/state version mismatch")
        lease = registry.get("lease")
        if isinstance(lease, dict):
            if state.get("loop_owner") != lease.get("owner"):
                issues.append("loop owner differs between state and lease")
            if not isinstance(lease.get("token_hash"), str) or len(lease["token_hash"]) != 64:
                issues.append("lease token hash is invalid")
        elif state.get("loop_owner") is not None:
            issues.append("state records a loop owner without a lease")
        workspaces = _need_dict(registry.get("workspaces", {}), "workspaces")
        integrators = [item for item in workspaces.values() if item.get("role") == "integrator"]
        if len(integrators) > 1:
            issues.append("multiple integrators are registered")
        paths: Dict[str, str] = {}
        writable = []
        for workspace_id, record in workspaces.items():
            issues.extend(verify_workspace_record(store, record))
            canonical = os.path.normcase(str(Path(record.get("path", "")).resolve(strict=False)))
            if canonical in paths:
                issues.append("workspaces share a path: %s and %s" % (paths[canonical], workspace_id))
            paths[canonical] = workspace_id
            if record.get("role") in WRITABLE_ROLES:
                writable.append((workspace_id, record))
        implementation_writers = [(workspace_id, record) for workspace_id, record in writable if record.get("role") in ("driver", "worker")]
        if len(implementation_writers) > 1:
            if len(integrators) != 1:
                issues.append("parallel writers require exactly one integrator")
            for workspace_id, record in implementation_writers:
                if not record.get("path_rules"):
                    issues.append("parallel writer has no path ownership rules: %s" % workspace_id)
        for index, (left_id, left) in enumerate(writable):
            for right_id, right in writable[index + 1 :]:
                for left_rule in left.get("path_rules", []):
                    for right_rule in right.get("path_rules", []):
                        if patterns_overlap(left_rule, right_rule):
                            issues.append(
                                "path rules overlap: %s:%s and %s:%s"
                                % (left_id, left_rule, right_id, right_rule)
                            )
        return {
            "ok": not issues,
            "issues": sorted(set(issues)),
            "state_version": state["version"],
            "phase": state["phase"],
            "effective_lease": effective_lease(registry),
            "evidence_events": len(events),
            "evidence_head": last_hash,
            "workspaces": len(workspaces),
        }


def _secret_like_paths(value: Any, prefix: str = "") -> List[str]:
    found: List[str] = []
    if isinstance(value, dict):
        for key, item in value.items():
            label = "%s.%s" % (prefix, key) if prefix else str(key)
            if any(word in str(key).lower() for word in ("token", "secret", "password", "credential", "api_key")):
                found.append(label)
            found.extend(_secret_like_paths(item, label))
    elif isinstance(value, list):
        for index, item in enumerate(value):
            found.extend(_secret_like_paths(item, "%s[%d]" % (prefix, index)))
    return found


def risk_decision(args: argparse.Namespace) -> Dict[str, Any]:
    reasons: List[str] = []
    score = 0
    weighted = [
        (args.cross_session, 2, "expected to cross sessions"),
        (args.architectural_boundaries >= 2, 2, "crosses multiple architecture boundaries"),
        (args.external_effects, 3, "has data, release, migration, or external side effects"),
        (args.multiple_writers, 3, "requires multiple writable workers"),
        (args.ambiguous_acceptance, 2, "acceptance criteria are ambiguous"),
        (args.high_failure_cost, 3, "failure cost is high"),
    ]
    for enabled, weight, reason in weighted:
        if enabled:
            score += weight
            reasons.append(reason)
    needed = bool(args.force or score >= 2)
    return {
        "schema_version": SCHEMA_VERSION,
        "contract": CONTRACT,
        "needed": needed,
        "score": score,
        "threshold": 2,
        "explicit": bool(args.force),
        "reasons": reasons,
    }


def _show_payload(store: TaskStore) -> Dict[str, Any]:
    state, registry = store.read()
    result = dict(state)
    result["lease"] = effective_lease(registry)
    result["workspaces"] = [
        {key: value for key, value in item.items() if key != "token_hash"}
        for item in _need_dict(registry.get("workspaces", {}), "workspaces").values()
    ]
    result["authority_root"] = str(store.authority_root(registry))
    return result


def _actor(args: argparse.Namespace) -> str:
    value = getattr(args, "actor", None) or os.environ.get("WORKCTL_ACTOR") or getpass.getuser()
    return value[:128]


def _emit(value: Mapping[str, Any], pretty: bool = False) -> None:
    json.dump(value, sys.stdout, sort_keys=True, ensure_ascii=False, indent=2 if pretty else None, allow_nan=False)
    sys.stdout.write("\n")


def _add_task_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("task_id")
    parser.add_argument("--repo", type=Path, default=Path.cwd())


def _add_mutation_args(parser: argparse.ArgumentParser, token: bool = True) -> None:
    parser.add_argument("--expect-version", type=int, required=True, help="required compare-and-swap state version")
    parser.add_argument("--actor", help="evidence actor; defaults to WORKCTL_ACTOR/current user")
    if token:
        parser.add_argument("--token", help="loop-owner token; prefer --token-file or WORKCTL_LEASE_TOKEN")
        parser.add_argument("--token-file", type=Path)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="workctl",
        description="Coordinate optional, evidence-backed agent work across Git worktrees.",
    )
    parser.add_argument("--pretty", action="store_true", help="pretty-print JSON output")
    sub = parser.add_subparsers(dest="command", required=True)

    risk = sub.add_parser("risk", help="deterministically decide whether task artifacts are warranted")
    risk.add_argument("--cross-session", action="store_true")
    risk.add_argument("--architectural-boundaries", type=int, default=1)
    risk.add_argument("--external-effects", action="store_true")
    risk.add_argument("--multiple-writers", action="store_true")
    risk.add_argument("--ambiguous-acceptance", action="store_true")
    risk.add_argument("--high-failure-cost", action="store_true")
    risk.add_argument("--force", action="store_true", help="explicit opt-in")

    init = sub.add_parser("init", help="initialize .agents/work/<task-id> in this authoritative worktree")
    init.add_argument("task_id")
    init.add_argument("--repo", type=Path, default=Path.cwd())
    init.add_argument("--title", default="")
    init.add_argument("--max-verify-retries", type=int, default=2)
    init.add_argument("--idempotent", action="store_true")

    show = sub.add_parser("show", help="show redacted state, lease, and workspace registry")
    _add_task_arg(show)

    verify = sub.add_parser("verify", help="verify schemas, evidence chain, lease, and workspaces")
    _add_task_arg(verify)

    doctor = sub.add_parser("doctor", help="check common-dir runtime and optionally a task")
    doctor.add_argument("--repo", type=Path, default=Path.cwd())
    doctor.add_argument("--task-id")

    transition = sub.add_parser("transition", help="perform a validated, token-checked state transition")
    _add_task_arg(transition)
    transition.add_argument("target", choices=sorted(PHASES))
    transition.add_argument("--reason", default="")
    _add_mutation_args(transition)

    evidence = sub.add_parser("evidence", help="append a sequenced, hash-chained evidence event")
    _add_task_arg(evidence)
    evidence.add_argument("--kind", required=True)
    evidence.add_argument("--payload", default="{}", help="JSON object; secrets must not be included")
    _add_mutation_args(evidence)

    owner = sub.add_parser("owner", help="acquire, check, heartbeat, recover, hand off, or release the single loop owner")
    owner_sub = owner.add_subparsers(dest="owner_command", required=True)
    for name in ("acquire", "recover"):
        cmd = owner_sub.add_parser(name)
        _add_task_arg(cmd)
        cmd.add_argument("owner")
        cmd.add_argument("--ttl", type=int, default=1800)
        _add_mutation_args(cmd, token=False)
    handoff = owner_sub.add_parser("handoff")
    _add_task_arg(handoff)
    handoff.add_argument("new_owner")
    handoff.add_argument("--ttl", type=int, default=1800)
    _add_mutation_args(handoff)
    check_owner_parser = owner_sub.add_parser("check")
    _add_task_arg(check_owner_parser)
    check_owner_parser.add_argument("--token", help="loop-owner token; prefer --token-file or WORKCTL_LEASE_TOKEN")
    check_owner_parser.add_argument("--token-file", type=Path)
    heartbeat = owner_sub.add_parser("heartbeat")
    _add_task_arg(heartbeat)
    heartbeat.add_argument("--ttl", type=int, default=1800)
    _add_mutation_args(heartbeat)
    release = owner_sub.add_parser("release")
    _add_task_arg(release)
    _add_mutation_args(release)

    workspace = sub.add_parser("workspace", help="manage isolated writable and fixed reviewer worktrees")
    workspace_sub = workspace.add_subparsers(dest="workspace_command", required=True)
    create = workspace_sub.add_parser("create")
    _add_task_arg(create)
    create.add_argument("workspace_id")
    create.add_argument("--role", choices=sorted(WORKSPACE_ROLES), required=True)
    create.add_argument("--path", type=Path, required=True)
    create.add_argument("--commit", help="required exact full SHA for reviewers")
    create.add_argument("--branch", help="required new branch for writable roles")
    create.add_argument("--start-point", default="HEAD")
    _add_mutation_args(create)
    claim = workspace_sub.add_parser("claim")
    _add_task_arg(claim)
    claim.add_argument("workspace_id")
    claim.add_argument("--path-rule", action="append", required=True)
    _add_mutation_args(claim)
    check = workspace_sub.add_parser("check")
    _add_task_arg(check)
    check.add_argument("workspace_id")
    remove = workspace_sub.add_parser("remove")
    _add_task_arg(remove)
    remove.add_argument("workspace_id")
    remove.add_argument("--merged-into", default="HEAD")
    remove.add_argument("--force", action="store_true")
    remove.add_argument("--reason", default="")
    _add_mutation_args(remove)
    prune = workspace_sub.add_parser("prune-stale")
    _add_task_arg(prune)
    prune.add_argument("workspace_id")
    prune.add_argument("--reason", required=True)
    _add_mutation_args(prune)
    guard = workspace_sub.add_parser("assert-write")
    _add_task_arg(guard)
    guard.add_argument("--cwd", type=Path, default=Path.cwd())

    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        if args.command == "risk":
            _emit(risk_decision(args), args.pretty)
            return EXIT_OK
        if args.command == "init":
            if args.max_verify_retries < 0 or args.max_verify_retries > 100:
                raise HarnessError("max verify retries must be 0..100", code=EXIT_USAGE)
            context = discover_git_context(args.repo)
            store, state = init_task(
                context, args.task_id, args.max_verify_retries, args.title, force_existing=args.idempotent
            )
            _emit({"ok": True, "task": state, "task_dir": str(store.task_dir())}, args.pretty)
            return EXIT_OK
        if args.command in ("show", "verify"):
            store = TaskStore.for_existing(args.repo, args.task_id)
            result = _show_payload(store) if args.command == "show" else verify_task(store)
            _emit({"ok": result.get("ok", True), "task": result}, args.pretty)
            return EXIT_OK if result.get("ok", True) else EXIT_VERIFY
        if args.command == "doctor":
            context = discover_git_context(args.repo)
            runtime = context.common_dir / RUNTIME_DIR_NAME
            result: Dict[str, Any] = {
                "ok": True,
                "contract": CONTRACT,
                "worktree_root": str(context.worktree_root),
                "git_common_dir": str(context.common_dir),
                "runtime_dir": str(runtime),
                "runtime_exists": runtime.exists(),
            }
            if args.task_id:
                task = verify_task(TaskStore.for_existing(args.repo, args.task_id))
                result["task"] = task
                result["ok"] = task["ok"]
            _emit(result, args.pretty)
            return EXIT_OK if result["ok"] else EXIT_VERIFY
        if args.command == "owner":
            store = TaskStore.for_existing(args.repo, args.task_id)
            actor = _actor(args)
            if args.owner_command == "check":
                state, lease = check_owner(store, _token_from_args(args))
                _emit({"ok": True, "version": state["version"], "owner": state["loop_owner"], "lease": lease}, args.pretty)
                return EXIT_OK
            if args.owner_command == "heartbeat":
                state = heartbeat_owner(
                    store, args.expect_version, _token_from_args(args), args.ttl, actor
                )
                _, lease = check_owner(store, _token_from_args(args))
                _emit({"ok": True, "version": state["version"], "owner": state["loop_owner"], "lease": lease}, args.pretty)
                return EXIT_OK
            if args.owner_command in ("acquire", "recover"):
                state, token = acquire_owner(
                    store,
                    args.expect_version,
                    args.owner,
                    args.ttl,
                    actor,
                    recover=args.owner_command == "recover",
                )
                _emit(
                    {
                        "ok": True,
                        "task_id": args.task_id,
                        "version": state["version"],
                        "owner": state["loop_owner"],
                        "lease_token": token,
                        "warning": "token is shown once; store it outside committed artifacts",
                    },
                    args.pretty,
                )
                return EXIT_OK
            token = _token_from_args(args)
            if args.owner_command == "handoff":
                state, new_token = handoff_owner(
                    store, args.expect_version, token, args.new_owner, args.ttl, actor
                )
                _emit(
                    {
                        "ok": True,
                        "version": state["version"],
                        "owner": state["loop_owner"],
                        "lease_token": new_token,
                        "warning": "old token is revoked; new token is shown once",
                    },
                    args.pretty,
                )
                return EXIT_OK
            state = release_owner(store, args.expect_version, token, actor)
            _emit({"ok": True, "version": state["version"], "owner": None}, args.pretty)
            return EXIT_OK
        if args.command == "transition":
            store = TaskStore.for_existing(args.repo, args.task_id)
            state = transition_task(
                store,
                args.expect_version,
                _token_from_args(args),
                args.target,
                _actor(args),
                args.reason,
            )
            _emit({"ok": True, "task": state}, args.pretty)
            return EXIT_OK
        if args.command == "evidence":
            try:
                payload = json.loads(args.payload)
            except json.JSONDecodeError as exc:
                raise HarnessError("--payload must be valid JSON", code=EXIT_USAGE) from exc
            if not isinstance(payload, dict):
                raise HarnessError("--payload must be a JSON object", code=EXIT_USAGE)
            if len(canonical_json(payload)) > 1024 * 1024:
                raise HarnessError("evidence payload exceeds 1 MiB", code=EXIT_DATA)
            forbidden = _secret_like_paths(payload)
            if forbidden:
                raise HarnessError("evidence payload contains secret-like keys: %s" % ", ".join(forbidden[:8]), code=EXIT_DATA)
            store = TaskStore.for_existing(args.repo, args.task_id)
            event = store.append_evidence(
                args.expect_version,
                _actor(args),
                args.kind,
                payload,
                _token_from_args(args),
            )
            _emit({"ok": True, "event": event, "version": args.expect_version + 1}, args.pretty)
            return EXIT_OK
        if args.command == "workspace":
            store = TaskStore.for_existing(args.repo, args.task_id)
            if args.workspace_command == "create":
                record = create_workspace(
                    store,
                    args.expect_version,
                    _token_from_args(args),
                    args.workspace_id,
                    args.role,
                    args.path,
                    _actor(args),
                    args.commit,
                    args.branch,
                    args.start_point,
                )
                _emit({"ok": True, "workspace": record, "version": args.expect_version + 1}, args.pretty)
                return EXIT_OK
            if args.workspace_command == "claim":
                record = claim_paths(
                    store,
                    args.expect_version,
                    _token_from_args(args),
                    args.workspace_id,
                    args.path_rule,
                    _actor(args),
                )
                _emit({"ok": True, "workspace": record, "version": args.expect_version + 1}, args.pretty)
                return EXIT_OK
            if args.workspace_command == "check":
                _, registry = store.read()
                record = _need_dict(registry.get("workspaces", {}), "workspaces").get(args.workspace_id)
                if not isinstance(record, dict):
                    raise HarnessError("unknown workspace", code=EXIT_WORKSPACE)
                issues = verify_workspace_record(store, record)
                _emit({"ok": not issues, "issues": issues, "workspace": record}, args.pretty)
                return EXIT_OK if not issues else EXIT_WORKSPACE
            if args.workspace_command == "remove":
                remove_workspace(
                    store,
                    args.expect_version,
                    _token_from_args(args),
                    args.workspace_id,
                    _actor(args),
                    args.merged_into,
                    args.force,
                    args.reason,
                )
                _emit({"ok": True, "removed": args.workspace_id, "version": args.expect_version + 1}, args.pretty)
                return EXIT_OK
            if args.workspace_command == "prune-stale":
                prune_stale_workspace(
                    store,
                    args.expect_version,
                    _token_from_args(args),
                    args.workspace_id,
                    _actor(args),
                    args.reason,
                )
                _emit({"ok": True, "pruned": args.workspace_id, "version": args.expect_version + 1}, args.pretty)
                return EXIT_OK
            if args.workspace_command == "assert-write":
                assert_writable_context(store, args.cwd)
                _emit({"ok": True, "writable": True}, args.pretty)
                return EXIT_OK
        parser.error("unsupported command")
    except HarnessError as exc:
        _emit({"ok": False, "error": str(exc), "code": exc.code, "details": exc.details}, getattr(args, "pretty", False))
        return exc.code
    return EXIT_USAGE


if __name__ == "__main__":
    raise SystemExit(main())
