#!/usr/bin/env python3
"""Ship one document-metadata contract in independently installable catalog skills."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "skills/project-docs-organizer/references/document-metadata.md"
TARGET = ROOT / "skills/agent-scaffold/assets/scaffold/document-metadata.md"
HEADER = (
    "<!-- Generated by scripts/generate_document_metadata.py; do not edit. "
    "Source: skills/project-docs-organizer/references/document-metadata.md. -->\n\n"
)


def synchronize(source: Path, target: Path, *, check: bool) -> bool:
    """Return false on drift in check mode; never follow output symlinks."""
    if source.is_symlink() or not source.is_file():
        raise ValueError("metadata source must be a regular file: %s" % source)
    if target.is_symlink() or (target.exists() and not target.is_file()):
        raise ValueError("metadata target must be a regular file: %s" % target)
    expected = HEADER.encode("utf-8") + source.read_bytes()
    if target.is_file() and target.read_bytes() == expected:
        return True
    if check:
        return False
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(expected)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report drift without writes")
    args = parser.parse_args()
    try:
        if synchronize(SOURCE, TARGET, check=args.check):
            return 0
    except (OSError, ValueError) as exc:
        parser.exit(1, "%s\n" % exc)
    parser.exit(1, "stale document metadata asset; run python scripts/generate_document_metadata.py\n")


if __name__ == "__main__":
    raise SystemExit(main())
