#!/usr/bin/env python3
"""Generate/check P0 runtime payloads for public and project-private skills.

Published and project-local skills must not import repository-local maintainer
modules at runtime. This generator copies the shared standard-library source
into each payload with a stable generated header, then emits a tiny direct CLI
entry point.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path
from typing import Dict

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "scripts" / "p0_runtime"
HEADER = "# Generated by scripts/generate_p0_runtimes.py; do not edit.\n"

TARGETS = {
    "skill-eval": {
        "module": "skill_eval",
        "entry": "skill_eval.py",
        "package": "skill_eval_runtime",
        "package_scope": "project-private",
        "target": ".agents/skills/skill-eval",
    },
    "work-protocol": {
        "module": "workctl",
        "entry": "workctl.py",
        "package": "work_protocol_runtime",
        "package_scope": "independently installable",
        "target": "skills/work-protocol",
    },
}


def _render_sources(package: str, module: str, package_scope: str, target_root: str) -> Dict[Path, str]:
    target = ROOT / target_root / "scripts"
    package_dir = target / package
    init_text = HEADER + '"""Generated, %s runtime package."""\n' % package_scope
    common_text = HEADER + (SOURCE / "common.py").read_text(encoding="utf-8")
    module_text = HEADER + (SOURCE / (module + ".py")).read_text(encoding="utf-8")
    entry_name = "skill_eval.py" if module == "skill_eval" else "workctl.py"
    entry_text = "#!/usr/bin/env python3\n" + HEADER + """from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
from {package}.{module} import main

raise SystemExit(main())
""".format(package=package, module=module)
    return {
        package_dir / "__init__.py": init_text,
        package_dir / "common.py": common_text,
        package_dir / (module + ".py"): module_text,
        target / entry_name: entry_text,
    }


def expected_files() -> Dict[Path, str]:
    files: Dict[Path, str] = {}
    for spec in TARGETS.values():
        files.update(
            _render_sources(
                spec["package"], spec["module"], spec["package_scope"], spec["target"]
            )
        )
    return files


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail instead of rewriting drifted payloads")
    args = parser.parse_args(argv)
    drift = []
    for path, expected in expected_files().items():
        actual = path.read_text(encoding="utf-8") if path.is_file() else None
        if actual == expected:
            continue
        drift.append(path.relative_to(ROOT).as_posix())
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            with path.open("w", encoding="utf-8", newline="\n") as handle:
                handle.write(expected)
            if path.name in ("skill_eval.py", "workctl.py") and path.parent.name == "scripts":
                try:
                    path.chmod(path.stat().st_mode | 0o111)
                except OSError:
                    pass
    if args.check and drift:
        print("generated P0 runtime drift:", file=sys.stderr)
        for item in drift:
            print("- " + item, file=sys.stderr)
        return 1
    action = "checked" if args.check else "generated"
    print("%s %d P0 runtime files" % (action, len(expected_files())))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
