#!/usr/bin/env python3
"""Generate self-contained workflow runtimes embedded in independently installable skills."""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path
from typing import Dict

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "scripts" / "workflow_runtime"
TARGETS: Dict[str, Path] = {
    "autopilot.py": ROOT / "skills" / "autopilot" / "scripts" / "autopilot_state.py",
    "deep_interview.py": ROOT / "skills" / "deep-interview" / "scripts" / "interview_state.py",
    "ralph.py": ROOT / "skills" / "ralph" / "scripts" / "ralph_state.py",
}
HEADER = """#!/usr/bin/env python3
# Generated by scripts/generate_workflow_runtimes.py. Do not edit this file directly.
# Source: scripts/workflow_runtime/common.py + scripts/workflow_runtime/{source}
"""


def render(source_name: str) -> str:
    common = (SOURCE / "common.py").read_text(encoding="utf-8").rstrip() + "\n"
    workflow = (SOURCE / source_name).read_text(encoding="utf-8").rstrip() + "\n"
    return HEADER.format(source=source_name) + "\n" + common + "\n\n" + workflow


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when generated runtimes are stale")
    args = parser.parse_args()

    stale = []
    for source_name, target in TARGETS.items():
        expected = render(source_name)
        actual = target.read_text(encoding="utf-8") if target.exists() else ""
        if actual == expected:
            continue
        if args.check:
            stale.append(str(target.relative_to(ROOT)))
            diff = difflib.unified_diff(
                actual.splitlines(),
                expected.splitlines(),
                fromfile=str(target.relative_to(ROOT)),
                tofile="generated",
                lineterm="",
                n=2,
            )
            for line in list(diff)[:80]:
                print(line, file=sys.stderr)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        with target.open("w", encoding="utf-8", newline="\n") as handle:
            handle.write(expected)
        target.chmod(0o755)
        print("generated %s" % target.relative_to(ROOT))

    if stale:
        print("stale generated runtimes: %s" % ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
