#!/usr/bin/env python3
# Generated by scripts/generate_p0_runtimes.py; do not edit.
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
from work_protocol_runtime.workctl import main

raise SystemExit(main())
